export * from './DashboardPage';
export * from './AdminDashboard';
export * from './EducationDashboard';
export * from './StudentDashboard';
export * from './PublicDashboard';
export * from '../../admin/pages/AdminListPage';
export * from '../../admin/pages/AdminDetailPage';
export * from '../../student/pages/StudentListPage';
export * from '../../student/pages/StudentDetailPage';
