import { Check, Users } from 'lucide-react';
import { AssistantShiftAvatar } from '../../assistantShift/components';
import { Button, Modal } from '../../../shared/components/ui';

const dateKey = (value) => new Date(value).toLocaleDateString('vi-VN', { weekday: 'short', day: '2-digit', month: '2-digit' });
const timeLabel = (value) => new Date(value).toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' });

const SelectablePerson = ({ admin, selected, disabled, onSelect }) => <button type="button" disabled={disabled} onClick={onSelect} className={`flex w-full items-center gap-3 rounded-lg border p-3 text-left transition ${selected ? 'border-violet-500 bg-violet-50' : 'border-border hover:border-violet-300 hover:bg-gray-50'}`}><AssistantShiftAvatar admin={admin} sizeClass="h-10 w-10" textClass="text-xs" /><span className="min-w-0 flex-1 truncate text-sm font-medium">{admin?.fullName || `Admin #${admin?.adminId}`}</span><span className={`flex h-5 w-5 items-center justify-center rounded border ${selected ? 'border-violet-600 bg-violet-600 text-white' : 'border-gray-300 bg-white'}`}>{selected && <Check className="h-3.5 w-3.5" />}</span></button>;

export const TransferAssistantShiftModal = ({ shift, assistants, loading, selectedAdminId, onSelect, saving, onClose, onConfirm, profile }) => {
  const candidates = assistants.filter((admin) => admin.adminId !== profile?.adminId && !shift?.assignments?.some((assignment) => assignment.adminId === admin.adminId));
  return <Modal isOpen={Boolean(shift)} onClose={onClose} title="Nhường ca"><div className="space-y-4"><p className="text-sm text-foreground-light">Chọn một trợ giảng để gửi đề nghị nhường ca “{shift?.name}”. Người nhận sẽ xác nhận qua email.</p><div className="max-h-80 space-y-2 overflow-auto pr-1">{loading ? <p className="rounded-lg bg-gray-50 p-4 text-sm text-foreground-light">Đang tải danh sách trợ giảng...</p> : candidates.map((admin) => <SelectablePerson key={admin.adminId} admin={admin} selected={selectedAdminId === admin.adminId} onSelect={() => onSelect(admin.adminId)} />)}{!loading && !candidates.length && <p className="rounded-lg bg-gray-50 p-4 text-sm text-foreground-light">Không có trợ giảng phù hợp.</p>}</div><div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Hủy</Button><Button disabled={!selectedAdminId} loading={saving} onClick={onConfirm}>Gửi đề nghị nhường ca</Button></div></div></Modal>;
};

export const SwapAssistantShiftModal = ({ targetShift, myShifts, loading, selectedAdminId, selectedMyShiftId, onSelectAdmin, onSelectMyShift, saving, onClose, onConfirm, profile }) => {
  const people = (targetShift?.assignments || []).filter((assignment) => assignment.adminId !== profile?.adminId && assignment.attendanceStatus === 'PENDING');
  return <Modal isOpen={Boolean(targetShift)} onClose={onClose} title="Đổi ca"><div className="space-y-4"><p className="text-sm text-foreground-light">Chọn trợ giảng đang ở ca này, rồi chọn một ca chờ xác nhận của bạn để gửi đề nghị đổi ca qua email.</p><div><p className="mb-2 text-sm font-semibold">Trợ giảng trong ca “{targetShift?.name}”</p><div className="max-h-48 space-y-2 overflow-auto pr-1">{people.map((assignment) => <SelectablePerson key={assignment.adminId} admin={assignment.admin} selected={selectedAdminId === assignment.adminId} onSelect={() => onSelectAdmin(assignment.adminId)} />)}{!people.length && <p className="rounded-lg bg-gray-50 p-3 text-sm text-foreground-light">Không có assignment PENDING để đổi.</p>}</div></div><div><div className="mb-2 flex items-center gap-2"><Users className="h-4 w-4 text-blue-600" /><p className="text-sm font-semibold">Lịch PENDING của bạn</p></div><div className="grid max-h-72 gap-2 overflow-auto rounded-lg border border-border bg-gray-50 p-2 sm:grid-cols-2">{loading ? <p className="p-3 text-sm text-foreground-light">Đang tải lịch...</p> : myShifts.filter((shift) => shift.assistantShiftId !== targetShift?.assistantShiftId).map((shift) => <button type="button" key={shift.assistantShiftId} onClick={() => onSelectMyShift(shift.assistantShiftId)} className={`rounded-lg border p-3 text-left transition ${selectedMyShiftId === shift.assistantShiftId ? 'border-blue-600 bg-blue-50' : 'border-border bg-white hover:border-blue-300'}`}><p className="text-xs font-medium text-foreground-light">{dateKey(shift.startAt)} · {timeLabel(shift.startAt)} – {timeLabel(shift.endAt)}</p><p className="mt-1 text-sm font-semibold">{shift.name}</p><p className="mt-1 truncate text-xs text-foreground-light">{shift.courseClass?.className || shift.courseClass?.name || shift.series?.name}</p></button>)}{!loading && !myShifts.length && <p className="p-3 text-sm text-foreground-light">Bạn không có ca PENDING để đổi.</p>}</div></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Hủy</Button><Button disabled={!selectedAdminId || !selectedMyShiftId} loading={saving} onClick={onConfirm}>Gửi đề nghị đổi ca</Button></div></div></Modal>;
};
