import { ChevronLeft, ChevronRight, CirclePlus, Copy, LayoutPanelTop, RefreshCw, UsersRound } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { PERMISSIONS } from '../../../core/constants/permission/permission.codes';
import { Button, Checkbox, ConfirmModal, Input, Modal } from '../../../shared/components/ui';
import { useHasPermission } from '../../../shared/hooks/permissions';
import { AdminSearchSelect } from '../../admin/components/AdminSearchSelect';
import { AssistantShiftDrawer, AssistantShiftMiniCalendar, AssistantShiftSidebar, AssistantShiftWeekCalendar } from '../components';
import {
  clearAssistantShiftDetail, copyAssistantShiftWeekAsync, createAssistantShiftAssignmentAsync, createAssistantShiftAsync, createAssistantShiftSeriesAsync,
  deleteAssistantShiftAssignmentAsync, deleteAssistantShiftAsync, getAssistantShiftByIdAsync, getAssistantShiftSeriesAsync,
  getAssistantShiftsBySeriesAsync, lockAssistantShiftWeekAsync, selectAssistantShiftAssignmentLoading, selectAssistantShiftDetail,
  selectAssistantShiftError, selectAssistantShiftLoadingDetail, selectAssistantShiftLoadingSeries, selectAssistantShiftLoadingShifts,
  selectAssistantShiftMap, selectAssistantShiftSaving, selectAssistantShiftSeries, setAssistantShiftRegistrationWindowAsync,
  unlockAssistantShiftWeekAsync, updateAssistantShiftAssignmentAsync, updateAssistantShiftAsync, updateAssistantShiftSeriesAsync,
} from '../store/assistantShiftSlice';

const dayString = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const mondayOf = (value) => { const date = new Date(value); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; };
const weekDaysFor = (monday) => Array.from({ length: 7 }, (_, index) => { const day = new Date(monday); day.setDate(monday.getDate() + index); return day; });
const weekRange = (days) => `${days[0].getDate()}/${days[0].getMonth() + 1} – ${days[6].getDate()}/${days[6].getMonth() + 1}/${days[6].getFullYear()}`;
const weekPayload = (start) => { const from = new Date(start); from.setHours(0, 0, 0, 0); const to = new Date(from); to.setDate(to.getDate() + 6); to.setHours(23, 59, 59, 999); return { startAt: from.toISOString(), endAt: to.toISOString() }; };

export const AssistantShiftCalendarPage = () => {
  const dispatch = useDispatch();
  const series = useSelector(selectAssistantShiftSeries); const shiftMap = useSelector(selectAssistantShiftMap); const detail = useSelector(selectAssistantShiftDetail);
  const loadingSeries = useSelector(selectAssistantShiftLoadingSeries); const loadingShifts = useSelector(selectAssistantShiftLoadingShifts); const loadingDetail = useSelector(selectAssistantShiftLoadingDetail);
  const saving = useSelector(selectAssistantShiftSaving); const assignmentLoading = useSelector(selectAssistantShiftAssignmentLoading); const error = useSelector(selectAssistantShiftError);
  const canReadShifts = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.GET_ALL_BY_SERIES); const canDetail = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.GET_DETAIL);
  const canCreateSeries = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.CREATE_SERIES); const canUpdateSeries = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.UPDATE_SERIES);
  const canCreate = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.CREATE); const canUpdate = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.UPDATE); const canDelete = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.DELETE);
  const canAssign = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.ASSIGN); const canUpdateAssignment = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.UPDATE_ASSIGNMENT); const canDeleteAssignment = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.DELETE_ASSIGNMENT);
  const canCopy = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.COPY); const canLockWeek = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.LOCK_BY_SERIES); const canUnlockWeek = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.UNLOCK_BY_SERIES); const canSetRegistrationWindow = useHasPermission(PERMISSIONS.ASSISTANT_SHIFT.SET_SELF_REGISTRATION_WINDOW_BY_SERIES);
  const [monday, setMonday] = useState(() => mondayOf(new Date())); const [visibleSeries, setVisibleSeries] = useState({}); const [selectedAdmin, setSelectedAdmin] = useState(null);
  const [drawerOpen, setDrawerOpen] = useState(false); const [drawerShift, setDrawerShift] = useState(null); const [drawerVersion, setDrawerVersion] = useState(0); const [cardFace, setCardFace] = useState('front');
  const [bulkAction, setBulkAction] = useState(null); const [copyOpen, setCopyOpen] = useState(false); const [copyAssignments, setCopyAssignments] = useState(true); const [registrationWindow, setRegistrationWindow] = useState(null);
  const [copyMonday, setCopyMonday] = useState(() => mondayOf(new Date())); const [pasteMonday, setPasteMonday] = useState(() => { const date = mondayOf(new Date()); date.setDate(date.getDate() + 7); return date; });
  const days = useMemo(() => weekDaysFor(monday), [monday]);
  const visibleIds = useMemo(() => series.filter((item) => visibleSeries[item.assistantShiftSeriesId] !== false).map((item) => item.assistantShiftSeriesId), [series, visibleSeries]);
  const shifts = useMemo(() => visibleIds.flatMap((id) => shiftMap[id] || []), [shiftMap, visibleIds]);
  const shownShift = drawerShift?.assistantShiftId && detail?.assistantShiftId === drawerShift.assistantShiftId ? detail : drawerShift;
  const selectedAdminId = selectedAdmin?.adminId || null;
  const loadSeries = useCallback(() => dispatch(getAssistantShiftSeriesAsync()), [dispatch]);
  const loadWeek = useCallback(() => { if (!canReadShifts) return Promise.resolve(); const params = { startAt: dayString(days[0]), endAt: dayString(days[6]), ...(selectedAdminId ? { adminId: selectedAdminId } : {}) }; return Promise.all(visibleIds.map((seriesId) => dispatch(getAssistantShiftsBySeriesAsync({ seriesId, params })))); }, [canReadShifts, days, dispatch, selectedAdminId, visibleIds]);
  useEffect(() => { loadSeries(); }, [loadSeries]); useEffect(() => { loadWeek(); }, [loadWeek]);
  const closeDrawer = () => { setDrawerOpen(false); setDrawerShift(null); dispatch(clearAssistantShiftDetail()); };
  const openCreate = (draft = null) => { if (!canCreate) return; setDrawerShift(draft || { assistantShiftSeriesId: visibleIds[0] || series[0]?.assistantShiftSeriesId || '' }); setDrawerVersion((value) => value + 1); setDrawerOpen(true); };
  const openShift = (shift) => { if (!canDetail) return; setDrawerShift(shift); setDrawerVersion((value) => value + 1); setDrawerOpen(true); dispatch(getAssistantShiftByIdAsync(shift.assistantShiftId)); };
  const slotClick = (day, minutes) => { const start = new Date(day); start.setHours(Math.floor(minutes / 60), minutes % 60, 0, 0); openCreate({ assistantShiftSeriesId: visibleIds[0] || '', startAt: start.toISOString(), endAt: new Date(start.getTime() + 3600000).toISOString(), requiredAssistantCount: 1 }); };
  const save = async (data) => { if (drawerShift?.assistantShiftId) await dispatch(updateAssistantShiftAsync({ id: drawerShift.assistantShiftId, data })).unwrap(); else await dispatch(createAssistantShiftAsync(data)).unwrap(); closeDrawer(); await loadWeek(); };
  const deleteShift = async () => { await dispatch(deleteAssistantShiftAsync(drawerShift.assistantShiftId)).unwrap(); closeDrawer(); await loadWeek(); };
  const reloadOpenShift = async () => { await dispatch(getAssistantShiftByIdAsync(drawerShift.assistantShiftId)); await loadWeek(); };
  const addAssignment = async (admin) => { await dispatch(createAssistantShiftAssignmentAsync({ shiftId: drawerShift.assistantShiftId, data: { adminId: admin.adminId, attendanceStatus: 'PENDING' } })).unwrap(); await reloadOpenShift(); };
  const updateAssignment = async (adminId, data) => { await dispatch(updateAssistantShiftAssignmentAsync({ shiftId: drawerShift.assistantShiftId, adminId, data: { ...data, absenceReason: data.absenceReason.trim() || null, managerNote: data.managerNote.trim() || null } })).unwrap(); await reloadOpenShift(); };
  const deleteAssignment = async (adminId) => { if (!window.confirm('Bỏ phân công trợ giảng này?')) return; await dispatch(deleteAssistantShiftAssignmentAsync({ shiftId: drawerShift.assistantShiftId, adminId })).unwrap(); await reloadOpenShift(); };
  const updateSeries = async (id, data) => { await dispatch(updateAssistantShiftSeriesAsync({ id, data })).unwrap(); await loadSeries(); };
  const createSeries = async (data) => { await dispatch(createAssistantShiftSeriesAsync(data)).unwrap(); await loadSeries(); };
  const runBulk = async () => { const data = weekPayload(monday); const creator = bulkAction.type === 'lock' ? lockAssistantShiftWeekAsync : unlockAssistantShiftWeekAsync; await dispatch(creator({ seriesId: bulkAction.series.assistantShiftSeriesId, data })).unwrap(); setBulkAction(null); await loadWeek(); };
  const copyWeek = async () => { const copy = weekPayload(copyMonday); const paste = weekPayload(pasteMonday); if (copyMonday.getTime() === pasteMonday.getTime()) return; const sourceResults = await Promise.all(visibleIds.map(async (seriesId) => ({ seriesId, result: await dispatch(getAssistantShiftsBySeriesAsync({ seriesId, params: { startAt: dayString(copyMonday), endAt: dayString(weekDaysFor(copyMonday)[6]) } })).unwrap() }))); const sourceSeriesIds = sourceResults.filter(({ result }) => result?.data?.length).map(({ seriesId }) => seriesId); if (!sourceSeriesIds.length) return; await Promise.all(sourceSeriesIds.map((seriesId) => dispatch(copyAssistantShiftWeekAsync({ seriesId, data: { startCopyAt: copy.startAt, endCopyAt: copy.endAt, startPasteAt: paste.startAt, endPasteAt: paste.endAt, copyAssignments } })).unwrap())); setCopyOpen(false); setMonday(pasteMonday); };
  const saveRegistrationWindow = async () => { if (!registrationWindow?.openAt || !registrationWindow?.closeAt || new Date(registrationWindow.closeAt) <= new Date(registrationWindow.openAt)) return; await dispatch(setAssistantShiftRegistrationWindowAsync({ seriesId: registrationWindow.series.assistantShiftSeriesId, data: { ...weekPayload(monday), selfRegistrationOpenAt: new Date(registrationWindow.openAt).toISOString(), selfRegistrationCloseAt: new Date(registrationWindow.closeAt).toISOString() } })).unwrap(); setRegistrationWindow(null); await loadWeek(); };
  const moveWeek = (offset) => setMonday((current) => { const next = new Date(current); next.setDate(next.getDate() + offset * 7); return next; });

  return <div className="flex min-h-full flex-col gap-4 2xl:h-full 2xl:min-h-0 2xl:overflow-hidden"><div className="shrink-0 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-sm font-medium text-blue-600">PHÂN CÔNG NHÂN SỰ</p><h1 className="mt-1 text-2xl font-semibold text-foreground">Lịch trợ giảng</h1><p className="mt-1 text-sm text-foreground-light">Quản lý lịch theo tuần, phân công và điểm danh trợ giảng cho từng ca.</p></div><div className="flex flex-wrap items-center gap-2"><div className="w-64"><AdminSearchSelect label="" placeholder="Lọc trợ giảng..." value={selectedAdmin} onSelect={setSelectedAdmin} /></div><Button variant="outline" size="sm" onClick={() => setMonday(mondayOf(new Date()))}>Hôm nay</Button><div className="flex items-center rounded-sm border border-border bg-white"><button type="button" aria-label="Tuần trước" onClick={() => moveWeek(-1)} className="p-2 hover:bg-gray-50"><ChevronLeft className="h-4 w-4" /></button><span className="min-w-40 px-2 text-center text-sm font-medium">{weekRange(days)}</span><button type="button" aria-label="Tuần sau" onClick={() => moveWeek(1)} className="p-2 hover:bg-gray-50"><ChevronRight className="h-4 w-4" /></button></div>{!selectedAdmin?.adminId && <div className="flex rounded-sm border border-border bg-white p-0.5"><button type="button" onClick={() => setCardFace('front')} className={`flex items-center gap-1 rounded px-2 py-1.5 text-xs font-medium ${cardFace === 'front' ? 'bg-blue-600 text-white shadow-sm' : 'text-foreground-light hover:bg-gray-50'}`}><LayoutPanelTop className="h-3.5 w-3.5" />Ca</button><button type="button" onClick={() => setCardFace('back')} className={`flex items-center gap-1 rounded px-2 py-1.5 text-xs font-medium ${cardFace === 'back' ? 'bg-indigo-600 text-white shadow-sm' : 'text-foreground-light hover:bg-gray-50'}`}><UsersRound className="h-3.5 w-3.5" />Trợ giảng</button></div>}{canCopy && <Button variant="outline" size="sm" onClick={() => { setCopyMonday(monday); const next = new Date(monday); next.setDate(next.getDate() + 7); setPasteMonday(next); setCopyAssignments(true); setCopyOpen(true); }}><Copy className="h-4 w-4" />Copy tuần</Button>}<Button variant="outline" size="sm" onClick={() => { loadSeries(); loadWeek(); }} loading={loadingSeries || loadingShifts}><RefreshCw className="h-4 w-4" />Làm mới</Button>{canCreate && <Button onClick={() => openCreate()}><CirclePlus className="h-4 w-4" />Tạo ca mới</Button>}</div></div>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">Không thể tải một phần dữ liệu lịch. Vui lòng thử lại.</div>}
    <div className="grid gap-5 2xl:min-h-0 2xl:flex-1 2xl:grid-cols-[288px_minmax(0,1fr)]"><AssistantShiftSidebar series={series} visibleSeries={visibleSeries} loading={loadingSeries} selectedWeekStart={monday} onSelectWeek={setMonday} canCreate={canCreateSeries} canUpdate={canUpdateSeries} canLockWeek={canLockWeek} canUnlockWeek={canUnlockWeek} canSetRegistrationWindow={canSetRegistrationWindow} onSetRegistrationWindow={(item) => setRegistrationWindow({ series: item, openAt: '', closeAt: '' })} onLockWeek={(item) => setBulkAction({ type: 'lock', series: item })} onUnlockWeek={(item) => setBulkAction({ type: 'unlock', series: item })} onVisibilityChange={(id, checked) => setVisibleSeries((current) => ({ ...current, [id]: checked }))} onCreate={createSeries} onUpdate={updateSeries} /><div className="h-[1280px] min-h-0 2xl:h-full">{canReadShifts ? <AssistantShiftWeekCalendar weekDays={days} shifts={shifts} loading={loadingShifts} cardFace={cardFace} filteredAdminId={selectedAdminId} canCreate={canCreate} onSlotClick={slotClick} onShiftClick={openShift} /> : <div className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-800">Bạn có thể xem chuỗi lịch nhưng chưa có quyền tải các ca trợ giảng.</div>}</div></div>
    <AssistantShiftDrawer key={drawerVersion} open={drawerOpen} onClose={closeDrawer} shift={shownShift} loadingDetail={Boolean(drawerShift?.assistantShiftId) && loadingDetail} series={series} saving={saving} permissions={{ create: canCreate, update: canUpdate, delete: canDelete, assign: canAssign, updateAssignment: canUpdateAssignment, deleteAssignment: canDeleteAssignment, assignmentLoading }} onSave={save} onDelete={deleteShift} onAddAssignment={addAssignment} onUpdateAssignment={updateAssignment} onDeleteAssignment={deleteAssignment} />
    <Modal isOpen={copyOpen} onClose={() => setCopyOpen(false)} title="Copy lịch tuần" size="xl"><div className="space-y-4"><p className="text-sm text-foreground-light">Cả hai dải tuần đều có thể di chuyển. COPY là tuần nguồn, PASTE là tuần nhận dữ liệu.</p><div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border border-violet-200 bg-violet-50 p-3"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-semibold uppercase text-violet-700">COPY · {weekRange(weekDaysFor(copyMonday))}</p><Button size="sm" variant="ghost" onClick={() => setCopyMonday(mondayOf(new Date()))}>Hôm nay</Button></div><AssistantShiftMiniCalendar key={copyMonday.toISOString()} selectedWeekStart={copyMonday} onSelectWeek={setCopyMonday} /></div><div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-semibold uppercase text-emerald-700">PASTE · {weekRange(weekDaysFor(pasteMonday))}</p><Button size="sm" variant="ghost" onClick={() => setPasteMonday(mondayOf(new Date()))}>Hôm nay</Button></div><AssistantShiftMiniCalendar key={pasteMonday.toISOString()} selectedWeekStart={pasteMonday} onSelectWeek={setPasteMonday} /></div></div><div className="rounded-lg border border-gray-200 bg-gray-50 px-3 py-2"><Checkbox id="copy-assignments" checked={copyAssignments} onChange={setCopyAssignments} label="Copy cả phân công trợ giảng" /><p className="ml-6 mt-1 text-xs text-foreground-light">Các phân công được copy về trạng thái PENDING, không mang lý do vắng và ghi chú quản lý.</p></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setCopyOpen(false)}>Hủy</Button><Button disabled={copyMonday.getTime() === pasteMonday.getTime()} loading={saving} onClick={copyWeek}><Copy className="h-4 w-4" />Copy sang tuần PASTE</Button></div></div></Modal>
    <Modal isOpen={Boolean(registrationWindow)} onClose={() => setRegistrationWindow(null)} title="Đặt cửa sổ tự đăng ký"><div className="space-y-4"><p className="text-sm text-foreground-light">Áp dụng cho chuỗi “{registrationWindow?.series?.name}” trong tuần {weekRange(days)}.</p><div className="grid gap-3 sm:grid-cols-2"><Input label="Mở đăng ký" type="datetime-local" value={registrationWindow?.openAt || ''} onChange={(event) => setRegistrationWindow((current) => ({ ...current, openAt: event.target.value }))} /><Input label="Đóng đăng ký" type="datetime-local" value={registrationWindow?.closeAt || ''} onChange={(event) => setRegistrationWindow((current) => ({ ...current, closeAt: event.target.value }))} /></div><p className="text-xs text-foreground-light">Thời điểm đóng phải sau thời điểm mở.</p><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setRegistrationWindow(null)}>Hủy</Button><Button loading={saving} disabled={!registrationWindow?.openAt || !registrationWindow?.closeAt || new Date(registrationWindow.closeAt) <= new Date(registrationWindow.openAt)} onClick={saveRegistrationWindow}>Lưu cửa sổ</Button></div></div></Modal>
    <ConfirmModal isOpen={Boolean(bulkAction)} onClose={() => setBulkAction(null)} onConfirm={runBulk} isLoading={saving} variant={bulkAction?.type === 'lock' ? 'warning' : 'info'} title={bulkAction?.type === 'lock' ? 'Khóa các ca trong tuần?' : 'Mở khóa các ca trong tuần?'} message={bulkAction ? `Áp dụng cho chuỗi “${bulkAction.series.name}” trong tuần ${weekRange(days)}.` : ''} confirmText={bulkAction?.type === 'lock' ? 'Khóa ca' : 'Mở khóa'} />
  </div>;
};
