import { CalendarClock, Save, Trash2, UsersRound } from 'lucide-react';
import { useMemo, useState } from 'react';
import { ClassSearchSelect } from '../../courseClass/components';
import { Button, Input, RightPanel, Textarea } from '../../../shared/components/ui';
import { AssistantShiftAssignmentManager } from './AssistantShiftAssignmentManager';

const timeOf = (value, fallback) => { const date = value ? new Date(value) : null; return date ? `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}` : fallback; };
const initial = (shift) => ({ assistantShiftSeriesId: shift?.assistantShiftSeriesId || '', classId: shift?.classId || '', selectedClass: shift?.courseClass || null, name: shift?.name || '', startTime: timeOf(shift?.startAt, '07:00'), endTime: timeOf(shift?.endAt, '08:00'), requiredAssistantCount: shift?.requiredAssistantCount || 1, notes: shift?.notes || '' });

export const AssistantShiftBaseDrawer = ({ open, shift, loadingDetail, series, weekday, saving, permissions, onClose, onSave, onDelete, onAddAssignment, onUpdateAssignment, onDeleteAssignment }) => {
  const editing = Boolean(shift?.assistantShiftId);
  const [form, setForm] = useState(() => initial(shift)); const [tab, setTab] = useState(editing ? 'assignments' : 'details');
  const assignments = useMemo(() => shift?.assignments || [], [shift]);
  const submit = async (event) => { event.preventDefault(); if ((!editing && !form.assistantShiftSeriesId) || !form.name.trim() || !form.startTime || !form.endTime || form.endTime <= form.startTime) return; await onSave({ ...(!editing ? { assistantShiftSeriesId: Number(form.assistantShiftSeriesId), weekday } : {}), classId: form.classId ? Number(form.classId) : null, name: form.name.trim(), startTime: form.startTime, endTime: form.endTime, requiredAssistantCount: Number(form.requiredAssistantCount), notes: form.notes.trim() || null }); };
  const canSave = editing ? permissions.update : permissions.create;

  return <RightPanel isOpen={open} onClose={onClose} title={editing ? 'Cập nhật ca cơ sở' : 'Tạo ca cơ sở'} width="w-full max-w-xl"><form className="space-y-4 p-5" onSubmit={submit}>{loadingDetail ? <div className="space-y-4 animate-pulse"><div className="h-10 rounded bg-gray-100" /><div className="h-10 rounded bg-gray-100" /><div className="h-48 rounded bg-gray-100" /></div> : <>
    <p className="rounded-lg bg-violet-50 p-3 text-sm text-violet-800"><CalendarClock className="mr-2 inline h-4 w-4" />{editing ? 'Ưu tiên phân công trợ giảng mẫu, sau đó có thể chuyển sang tab chỉnh sửa.' : 'Ca cơ sở là mẫu lịch lặp theo thứ trong tuần.'}</p>
    {editing && <div className="grid grid-cols-2 rounded-lg bg-gray-100 p-1"><button type="button" onClick={() => setTab('assignments')} className={`flex items-center justify-center gap-1 rounded-md px-3 py-2 text-sm font-medium ${tab === 'assignments' ? 'bg-white text-foreground shadow-sm' : 'text-foreground-light'}`}><UsersRound className="h-4 w-4" />Phân công</button><button type="button" onClick={() => setTab('details')} className={`rounded-md px-3 py-2 text-sm font-medium ${tab === 'details' ? 'bg-white text-foreground shadow-sm' : 'text-foreground-light'}`}>Chỉnh sửa</button></div>}
    {(!editing || tab === 'details') && <div className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-foreground">Chuỗi lịch <span className="text-red-500">*</span><select disabled={!canSave || saving || editing} value={form.assistantShiftSeriesId} onChange={(event) => setForm({ ...form, assistantShiftSeriesId: event.target.value })} className="mt-1 w-full rounded-sm border border-border bg-primary px-3 py-2 text-sm"><option value="">Chọn chuỗi lịch</option>{series?.map((item) => <option key={item.assistantShiftSeriesId} value={item.assistantShiftSeriesId}>{item.name}</option>)}</select></label><ClassSearchSelect label="Lớp học" value={form.selectedClass} disabled={!canSave || saving} onSelect={(courseClass) => setForm((current) => ({ ...current, selectedClass: courseClass, classId: courseClass?.classId || '', name: current.name || courseClass?.className || '' }))} /></div><Input label="Tên ca" value={form.name} required disabled={!canSave || saving} onChange={(event) => setForm({ ...form, name: event.target.value })} /><div className="grid grid-cols-2 gap-3"><Input label="Bắt đầu" type="time" value={form.startTime} required disabled={!canSave || saving} onChange={(event) => setForm({ ...form, startTime: event.target.value })} /><Input label="Kết thúc" type="time" value={form.endTime} required disabled={!canSave || saving} onChange={(event) => setForm({ ...form, endTime: event.target.value })} /></div><Input label="Số trợ giảng cần" type="number" min="1" value={form.requiredAssistantCount} required disabled={!canSave || saving} onChange={(event) => setForm({ ...form, requiredAssistantCount: event.target.value })} /><Textarea label="Ghi chú" value={form.notes} rows={3} disabled={!canSave || saving} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></div>}
    {editing && tab === 'assignments' && <AssistantShiftAssignmentManager assignments={assignments} disabled={saving} loading={permissions.assignmentLoading} canAssign={permissions.assign} canSearchAssistants={permissions.getAssistants} canUpdate={permissions.updateAssignment} canDelete={permissions.deleteAssignment} onAdd={onAddAssignment} onUpdate={onUpdateAssignment} onDelete={onDeleteAssignment} />}
    <div className="flex justify-between border-t border-border pt-4">{editing && permissions.delete ? <Button type="button" variant="danger" onClick={onDelete} disabled={saving}><Trash2 className="h-4 w-4" />Xóa</Button> : <span />}{canSave && (!editing || tab === 'details') && <Button type="submit" loading={saving}><Save className="h-4 w-4" />Lưu</Button>}</div>
  </>}</form></RightPanel>;
};
