import { CheckCircle2, Clock3, LockKeyhole, Plus, Users, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { EmptyState } from '../../../shared/components/ui';
import { AssistantShiftCalendarStats } from './AssistantShiftCalendarStats';
import { AssistantShiftAvatar } from './AssistantShiftAvatar';

const START = 7; const END = 22; const BASE_HEIGHT = 76;
const DAYS = ['Thứ Hai', 'Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu', 'Thứ Bảy', 'Chủ nhật'];
const STATUS = { PENDING: { label: 'Chờ', className: 'bg-amber-100 text-amber-800' }, PRESENT: { label: 'Có mặt', className: 'bg-emerald-100 text-emerald-800' }, ABSENT: { label: 'Vắng', className: 'bg-red-100 text-red-800' } };
const FILTERED_STATUS = {
  PENDING: { label: 'Chưa đi', card: 'border-blue-200 bg-blue-50 text-blue-950', badge: 'bg-blue-600 text-white', icon: Clock3 },
  PRESENT: { label: 'Đã đi', card: 'border-emerald-200 bg-emerald-50 text-emerald-950', badge: 'bg-emerald-600 text-white', icon: CheckCircle2 },
  ABSENT: { label: 'Nghỉ', card: 'border-red-200 bg-red-50 text-red-950', badge: 'bg-red-600 text-white', icon: XCircle },
};
const keyOf = (value) => { const date = new Date(value); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; };
const sameDay = (a, b) => keyOf(a) === keyOf(b); const mins = (value) => { const date = new Date(value); return date.getHours() * 60 + date.getMinutes(); }; const clamp = (value) => Math.max(START * 60, Math.min(END * 60, value));
const time = (value) => new Intl.DateTimeFormat('vi-VN', { hour: '2-digit', minute: '2-digit' }).format(new Date(value));
// Mặt sau hiển thị một hàng cho từng trợ giảng. Lưới sẽ giãn theo chiều cao này trước khi render card.
const cardHeight = (shift, filteredAdminId) => filteredAdminId ? 86 : Math.max(96, 52 + (shift.assignments?.length || 0) * 28);

const createScale = (shifts, filteredAdminId) => {
  const rows = Array.from({ length: END - START }, () => BASE_HEIGHT);
  const position = (value) => { const minute = clamp(value); if (minute === END * 60) return rows.reduce((sum, height) => sum + height, 0); const offset = minute - START * 60; const index = Math.min(rows.length - 1, Math.floor(offset / 60)); return rows.slice(0, index).reduce((sum, height) => sum + height, 0) + ((offset % 60) / 60) * rows[index]; };
  shifts.forEach((shift) => { const start = clamp(mins(shift.startAt)); const end = Math.max(start + 1, clamp(mins(shift.endAt))); const extra = cardHeight(shift, filteredAdminId) - (position(end) - position(start)); if (extra <= 0) return; const coverage = rows.map((_, index) => Math.max(0, Math.min(end, (START + index + 1) * 60) - Math.max(start, (START + index) * 60)) / 60); const totalCoverage = coverage.reduce((sum, value) => sum + value, 0); coverage.forEach((value, index) => { if (value) rows[index] += extra / totalCoverage; }); });
  const minuteAt = (offset) => { let left = Math.max(0, offset); for (let index = 0; index < rows.length; index += 1) { if (left <= rows[index]) return START * 60 + index * 60 + Math.floor(left / rows[index] * 2) * 30; left -= rows[index]; } return END * 60 - 30; };
  return { rows, position, minuteAt, height: rows.reduce((sum, value) => sum + value, 0) };
};

const EventCard = ({ shift, top, height, face, filteredAdminId, onClick }) => {
  const [hovered, setHovered] = useState(false); const assignments = shift.assignments || []; const showBack = face === 'back' ? !hovered : hovered;
  if (filteredAdminId) {
    const assignment = assignments.find((item) => Number(item.adminId) === Number(filteredAdminId)) || assignments[0];
    const status = FILTERED_STATUS[assignment?.attendanceStatus] || FILTERED_STATUS.PENDING;
    const Icon = status.icon;
    return <button data-shift-card="true" type="button" aria-label={`Mở ca ${shift.name}`} onClick={onClick} className={`absolute left-1 right-1 z-10 rounded-md border px-2 py-2 text-left shadow-sm transition hover:z-20 hover:shadow-md ${status.card}`} style={{ top, height }}><div className="flex h-full flex-col justify-between gap-2"><div><div className="flex items-start justify-between gap-1"><span className="line-clamp-2 text-xs font-semibold leading-snug">{shift.name}</span>{shift.isLocked && <LockKeyhole className="h-3.5 w-3.5 shrink-0 text-amber-600" />}</div><p className="mt-1 text-[11px] font-medium opacity-75">{time(shift.startAt)} – {time(shift.endAt)}</p></div><span className={`inline-flex w-fit items-center gap-1 rounded-full px-2 py-1 text-[10px] font-semibold ${status.badge}`}><Icon className="h-3 w-3" />{status.label}</span></div></button>;
  }
  return <button data-shift-card="true" type="button" aria-label={`Mở ca ${shift.name}`} onClick={onClick} onMouseEnter={() => setHovered(true)} onMouseLeave={() => setHovered(false)} onFocus={() => setHovered(true)} onBlur={() => setHovered(false)} className="group absolute left-1 right-1 z-10 text-left [perspective:900px] hover:z-20" style={{ top, height }}><div className="relative h-full transition-transform duration-500 [transform-style:preserve-3d]" style={{ transform: showBack ? 'rotateY(180deg)' : 'rotateY(0deg)' }}><div className="absolute inset-0 overflow-hidden rounded-md border border-blue-200 bg-blue-50 px-2 py-1.5 shadow-sm [backface-visibility:hidden]"><div className="flex items-start justify-between gap-1"><span className="line-clamp-1 text-xs font-semibold text-blue-900">{shift.name}</span>{shift.isLocked && <LockKeyhole className="h-3.5 w-3.5 shrink-0 text-amber-600" />}</div><p className="mt-0.5 text-[11px] text-blue-700">{time(shift.startAt)} – {time(shift.endAt)}</p><p className="line-clamp-1 text-[11px] text-blue-700">{shift.courseClass?.className || shift.courseClass?.name || shift.series?.name || 'Chưa gắn lớp'}</p><div className="mt-1 flex items-start justify-between gap-1"><div className="flex flex-wrap gap-0.5">{assignments.map((item) => <AssistantShiftAvatar key={item.adminId} admin={item.admin} status={item.attendanceStatus} sizeClass="h-4 w-4" textClass="text-[7px]" />)}</div><span className="flex shrink-0 items-center gap-0.5 text-[10px] font-medium text-blue-700"><Users className="h-3 w-3" />{assignments.length}/{shift.requiredAssistantCount}</span></div></div><div className="absolute inset-0 overflow-hidden rounded-md border border-indigo-200 bg-indigo-50 px-2 py-1.5 shadow-sm [backface-visibility:hidden] [transform:rotateY(180deg)]"><p className="line-clamp-1 text-[9px] font-semibold uppercase tracking-wide text-indigo-500">{shift.name}</p><div className="mt-1 space-y-1">{assignments.length ? assignments.map((item) => { const status = STATUS[item.attendanceStatus] || STATUS.PENDING; return <div key={item.adminId} className="flex items-center gap-1"><AssistantShiftAvatar admin={item.admin} status={item.attendanceStatus} sizeClass="h-5 w-5" textClass="text-[8px]" /><span className="min-w-0 flex-1 truncate text-[11px] font-medium text-indigo-950">{item.admin?.fullName || `Admin #${item.adminId}`}</span><span className={`shrink-0 rounded-full px-1.5 py-0.5 text-[9px] font-semibold ${status.className}`}>{status.label}</span></div>; }) : <p className="pt-2 text-center text-[11px] text-indigo-500">Chưa phân công trợ giảng</p>}</div></div></div></button>;
};

const DayColumn = ({ day, shifts, scale, canCreate, face, filteredAdminId, onSlotClick, onShiftClick }) => {
  const [preview, setPreview] = useState(null); const isCard = (event) => event.target.closest?.('[data-shift-card]'); const minuteAt = (event) => { const rect = event.currentTarget.getBoundingClientRect(); return scale.minuteAt(event.clientY - rect.top); };
  return <div role="button" tabIndex={0} onMouseMove={(event) => { if (canCreate && !filteredAdminId && !isCard(event)) setPreview(minuteAt(event)); }} onMouseLeave={() => setPreview(null)} onClick={(event) => { if (!isCard(event) && !filteredAdminId) onSlotClick(day, minuteAt(event)); }} onKeyDown={() => {}} className={`relative border-r border-border ${canCreate && !filteredAdminId ? 'cursor-crosshair' : ''}`} style={{ height: scale.height }}>{scale.rows.slice(1).map((_, index) => <span key={index} className="pointer-events-none absolute inset-x-0 border-t border-gray-200" style={{ top: scale.position((START + index + 1) * 60) }} />)}{preview !== null && <div className="pointer-events-none absolute left-1 right-1 z-20 rounded-md border border-slate-500 bg-slate-800/35" style={{ top: scale.position(preview), height: scale.position(Math.min(END * 60, preview + 60)) - scale.position(preview) }}><Plus className="absolute right-1.5 top-1/2 h-5 w-5 -translate-y-1/2 rounded-full bg-slate-800 p-1 text-white" /></div>}{shifts.map((shift) => { const start = clamp(mins(shift.startAt)); const end = Math.max(start + 1, clamp(mins(shift.endAt))); return <EventCard key={shift.assistantShiftId} shift={shift} top={scale.position(start)} height={Math.max(cardHeight(shift, filteredAdminId), scale.position(end) - scale.position(start))} face={face} filteredAdminId={filteredAdminId} onClick={(event) => { event.stopPropagation(); onShiftClick(shift); }} />; })}</div>;
};

export const AssistantShiftWeekCalendar = ({ weekDays, shifts, loading, cardFace, filteredAdminId, canCreate, onSlotClick, onShiftClick }) => {
  const scale = useMemo(() => createScale(shifts, filteredAdminId), [filteredAdminId, shifts]); const today = new Date();
  return <div className="relative h-full min-h-0 overflow-auto rounded-xl border border-border bg-white shadow-sm"><div className="min-w-[1020px]"><div className="sticky top-0 z-30 shadow-sm"><div className="grid grid-cols-[64px_repeat(7,minmax(130px,1fr))] border-b border-border bg-gray-50"><div />{weekDays.map((day) => <div key={keyOf(day)} className={`border-l border-border px-3 py-3 text-center text-sm font-semibold ${sameDay(day, today) ? 'bg-blue-600 text-white' : 'text-foreground'}`}>{DAYS[(day.getDay() + 6) % 7]} {day.getDate()}/{day.getMonth() + 1}</div>)}</div><AssistantShiftCalendarStats shifts={shifts} /></div><div className="grid grid-cols-[64px_repeat(7,minmax(130px,1fr))]"><div className="relative border-r border-border" style={{ height: scale.height }}>{Array.from({ length: END - START + 1 }).map((_, index) => <span key={index} className="absolute -top-2 right-2 text-xs text-foreground-light" style={{ top: scale.position((START + index) * 60) }}>{`${String(START + index).padStart(2, '0')}:00`}</span>)}</div>{weekDays.map((day) => <DayColumn key={keyOf(day)} day={day} shifts={shifts.filter((shift) => sameDay(shift.startAt, day))} scale={scale} canCreate={canCreate} face={cardFace} filteredAdminId={filteredAdminId} onSlotClick={onSlotClick} onShiftClick={onShiftClick} />)}</div>{!shifts.length && <EmptyState size="sm" icon="clipboard_list" title={filteredAdminId ? 'Trợ giảng này chưa có ca trong tuần' : 'Tuần này chưa có ca trợ giảng'} description={filteredAdminId ? 'Không có ca nào được phân công cho trợ giảng đang lọc.' : canCreate ? 'Di chuột trong lịch để xem trước vị trí, sau đó bấm để tạo ca.' : 'Chưa có ca trợ giảng trong tuần này.'} />}</div>{loading && <div className="absolute inset-0 z-40 flex items-center justify-center bg-slate-950/35 backdrop-blur-[1px]"><div className="flex items-center gap-3 rounded-lg bg-white px-4 py-3 text-sm font-medium text-foreground shadow-xl"><span className="h-5 w-5 animate-spin rounded-full border-2 border-blue-600 border-t-transparent" />Đang tải ca trợ giảng…</div></div>}</div>;
};
