import { Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { AdminSearchSelect } from '../../admin/components/AdminSearchSelect';
import { Button, Input, Textarea } from '../../../shared/components/ui';
import { AssistantShiftAvatar } from './AssistantShiftAvatar';

const STATUS = [{ value: 'PENDING', label: 'Chờ điểm danh' }, { value: 'PRESENT', label: 'Có mặt' }, { value: 'ABSENT', label: 'Vắng mặt' }];

export const AssistantShiftAssignmentManager = ({ assignments, disabled, loading, canAssign, canUpdate, canDelete, onAdd, onUpdate, onDelete }) => {
  const [admin, setAdmin] = useState(null); const [drafts, setDrafts] = useState({});
  const valueFor = (assignment) => drafts[assignment.adminId] || { attendanceStatus: assignment.attendanceStatus || 'PENDING', absenceReason: assignment.absenceReason || '', managerNote: assignment.managerNote || '' };
  const updateDraft = (adminId, field, value) => setDrafts((current) => ({ ...current, [adminId]: { ...valueFor(assignments.find((item) => item.adminId === adminId)), [field]: value } }));
  const add = async () => { if (!admin) return; await onAdd(admin); setAdmin(null); };
  return <section className="border-t border-border pt-5"><div className="mb-3 flex items-center justify-between"><div><h3 className="font-semibold text-foreground">Phân công trợ giảng</h3><p className="text-xs text-foreground-light">Tìm admin, phân công và theo dõi điểm danh.</p></div><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700">{assignments.length} người</span></div>
    {canAssign && <div className="mb-4 rounded-lg bg-gray-50 p-3"><AdminSearchSelect label="Thêm trợ giảng" placeholder="Tìm theo tên hoặc email..." value={admin} onSelect={setAdmin} disabled={disabled || loading} /><Button size="sm" className="mt-2" onClick={add} disabled={!admin || assignments.some((item) => item.adminId === admin.adminId)} loading={loading}><Plus className="h-4 w-4" />Phân công</Button></div>}
    <div className="space-y-3">{assignments.map((assignment) => { const draft = valueFor(assignment); return <div key={assignment.adminId} className="rounded-lg border border-border p-3"><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2"><AssistantShiftAvatar admin={assignment.admin} sizeClass="h-9 w-9" textClass="text-xs" /><div className="min-w-0"><p className="truncate text-sm font-medium">{assignment.admin?.fullName || `Admin #${assignment.adminId}`}</p><p className="text-xs text-foreground-light">ID: {assignment.adminId}</p></div></div>{canDelete && <Button size="sm" variant="ghost" disabled={disabled || loading} onClick={() => onDelete(assignment.adminId)}><Trash2 className="h-4 w-4 text-red-600" /></Button>}</div><div className="mt-3 grid gap-3"><label className="text-sm font-medium text-foreground">Điểm danh<select disabled={disabled || !canUpdate} value={draft.attendanceStatus} onChange={(event) => updateDraft(assignment.adminId, 'attendanceStatus', event.target.value)} className="mt-1 w-full rounded-sm border border-border bg-primary px-3 py-2 text-sm">{STATUS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{draft.attendanceStatus === 'ABSENT' && <Input label="Lý do vắng" value={draft.absenceReason} onChange={(event) => updateDraft(assignment.adminId, 'absenceReason', event.target.value)} disabled={disabled || !canUpdate} /> }<Textarea label="Ghi chú quản lý" value={draft.managerNote} onChange={(event) => updateDraft(assignment.adminId, 'managerNote', event.target.value)} disabled={disabled || !canUpdate} rows={2} maxLength={500} />{canUpdate && <div className="flex justify-end"><Button size="sm" variant="outline" disabled={disabled || loading} onClick={() => onUpdate(assignment.adminId, draft)} loading={loading}>Lưu phân công</Button></div>}</div></div>; })}</div>
    {!assignments.length && <p className="rounded-lg border border-dashed border-border p-4 text-center text-sm text-foreground-light">Chưa phân công trợ giảng cho ca này.</p>}
  </section>;
};
