// API Base URL
export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:3001/api";

// Storage Keys
export const STORAGE_KEYS = {
  ACCESS_TOKEN: "admin_access_token",
  REFRESH_TOKEN: "admin_refresh_token",
  USER_INFO: "user_info",
  USER: "user",
  SIDEBAR_OPEN: "sidebar_open",
};

// Routes
export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  SUPER_ADMIN: "/super-admin",
  PROFILE: "/profile",
  PROFILE_INFO: "/profile/info",
  PROFILE_PERMISSIONS: "/profile/permissions",
  PROFILE_SECURITY: "/profile/security",
  SETTINGS: "/settings",
  NOT_FOUND: '/404',
  FORBIDDEN: '/403',
  LOADING_REDIRECT: '/loading',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: (id) => `/roles/${id}/edit`,
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  PERMISSIONS_EDIT: (id) => `/permissions/${id}/edit`,
  AUDIT_LOGS: '/audit-logs',
  MEDIA: '/media',
  MEDIA_FOLDERS: '/media-folders',
  SEO_SLOTS: '/seo/slots',
  SEO_PAGES: '/seo/pages',
  ACHIEVEMENT_BOARDS: '/seo/achievement-boards',
  ADMINS: '/admins',
  ADMIN_DETAIL: (id = ':id') => `/admins/${id}`,
  ADMIN_ROLES: (id = ':id') => `/admins/${id}/roles`,
  ADMIN_MEDIA: (id = ':id') => `/admins/${id}/media`,
  ADMIN_AUDIT_LOGS: (id = ':id') => `/admins/${id}/audit-logs`,
  STUDENTS: '/students',
  STUDENT_DETAIL: (id = ':id') => `/students/${id}`,
  STUDENT_ROLES: (id = ':id') => `/students/${id}/roles`,
  STUDENT_MEDIA: (id = ':id') => `/students/${id}/media`,
  STUDENT_CLASSES: (id = ':id') => `/students/${id}/classes`,
  STUDENT_COURSES: (id = ':id') => `/students/${id}/courses`,
  STUDENT_ATTENDANCE: (id = ':id') => `/students/${id}/attendance`,
  STUDENT_POINT_LOGS: (id = ':id') => `/students/${id}/point-logs`,
  STUDENT_HOMEWORK_SUBMITS: (id = ':id') => `/students/${id}/homework-submits`,
  STUDENT_COMPETITION_SUBMITS: (id = ':id') => `/students/${id}/competition-submits`,
  SUBJECTS: '/subjects',
  SUBJECT_DETAIL: (id = ':id') => `/subjects/${id}`,
  TAGS: '/tags',
  TAG_DETAIL: (id = ':id') => `/tags/${id}`,
  DOCUMENTS: '/documents',
  DOCUMENT_CREATE: '/documents/create',
  DOCUMENT_DETAIL: (id = ':id') => `/documents/${id}`,
  DOCUMENT_EDIT: (id = ':id') => `/documents/${id}/edit`,
  TEACHER_PROFILES: '/teacher-profiles',
  TEACHER_PROFILE_CREATE: '/teacher-profiles/create',
  TEACHER_PROFILE_DETAIL: (id = ':id') => `/teacher-profiles/${id}`,
  TEACHER_PROFILE_EDIT: (id = ':id') => `/teacher-profiles/${id}/edit`,
  NEWS_ARTICLES: '/news-articles',
  NEWS_ARTICLE_CREATE: '/news-articles/create',
  NEWS_ARTICLE_DETAIL: (id = ':id') => `/news-articles/${id}`,
  NEWS_ARTICLE_EDIT: (id = ':id') => `/news-articles/${id}/edit`,
  CHAPTERS: '/chapters',
  CHAPTER_DETAIL: (id = ':id') => `/chapters/${id}`,
  COURSES: '/courses',
  MY_COURSES: '/my-courses',
  COURSE_DETAIL: (id = ':id') => `/courses/${id}`,
  COURSE_PRICING: (id = ':id') => `/courses/${id}/pricing`,
  COURSE_CLASSES: (id = ':id') => `/courses/${id}/classes`,
  COURSE_STUDENTS: (id = ':id') => `/courses/${id}/students`,
  COURSE_ATTENDANCE: (id = ':id') => `/courses/${id}/attendance`,
  COURSE_LESSONS: (id = ':id') => `/courses/${id}/lessons`,
  COURSE_MEDIA: (id = ':id') => `/courses/${id}/media`,
  CLASSES: '/classes',
  MY_CLASSES: '/my-classes',
  CLASS_DETAIL: (id = ':id') => `/classes/${id}`,
  CLASS_STUDENTS: (id = ':id') => `/classes/${id}/students`,
  CLASS_SESSIONS: (id = ':id') => `/classes/${id}/sessions`,
  CLASS_SCHEDULE: (id = ':id') => `/classes/${id}/schedule`,
  CLASS_ATTENDANCE: (id = ':id') => `/classes/${id}/attendance`,
  CLASS_NOTIFICATIONS: (id = ':id') => `/classes/${id}/notifications`,
  BROADCAST_NOTIFICATIONS: '/notifications/broadcast',
  NOTIFICATION_LOGS: '/notifications/logs',
  TUITION_PAYMENTS: '/tuition-payments',
  ONLINE_COURSE_INVOICES: '/online-course-invoices',
  BANK_TRANSFER_TRANSACTIONS: '/bank-transfer-transactions',
  RECEIVING_BANK_ACCOUNTS: '/receiving-bank-accounts',
  TUITION_COLLECTION_CONFIGURATION: '/tuition-collection-configuration',
  TUITION_GRADE_BANK_ACCOUNTS: '/tuition-grade-bank-accounts',
  BACKGROUND_JOBS: '/background-jobs',
  BACKGROUND_JOB_RUNS: '/background-job-runs',
  SEPAY_SYNC_CURSORS: '/sepay-sync-cursors',
  ASSISTANT_SHIFTS: '/assistant-shifts',
  ASSISTANT_SHIFT_REGISTRATION: '/assistant-shift-registration',
  MY_ASSISTANT_SCHEDULE: '/my-assistant-schedule',
  EXAM_IMPORT_SESSIONS: '/exam-import-sessions',
  EXAM_IMPORT_SESSION_DETAIL: (id = ':id') => `/exam-import-sessions/${id}`,
  EXAM_IMPORT_SESSION_UPLOAD: (id = ':id') => `/exam-import-sessions/${id}/upload`,
  EXAM_IMPORT_SESSION_PROCESS: (id = ':id') => `/exam-import-sessions/${id}/process`,
  EXAM_IMPORT_SESSION_PREVIEW: (id = ':id') => `/exam-import-sessions/${id}/preview`,
  QUESTIONS: '/questions',
  MY_QUESTIONS: '/my-questions',
  EXAMS: '/exams',
  MY_EXAMS: '/my-exams',
  EXAM_DETAIL: (id = ':id') => `/exams/${id}`,
  EXAM_QUESTIONS: (id = ':id') => `/exams/${id}/questions`,
  EXAM_PREVIEW: (id = ':id') => `/exams/${id}/preview`,
  COMPETITIONS: '/competitions',
  MY_COMPETITIONS: '/my-competitions',
  COMPETITION_DETAIL: (id = ':id') => `/competitions/${id}`,
};

// API Endpoints
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/admin/login",
    REGISTER: "/auth/admin/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/admin/me",
  },
  PROFILE: {
    GET: "admin/profile",
    UPDATE: "admin/profile",
    UPLOAD_AVATAR: "/admin/profile/avatar",
  },
  USERS: {
    LIST: "/users",
    DETAIL: (id) => `/users/${id}`,
    TOGGLE_ACTIVATION: (id) => `/users/${id}/toggle-activation`,
    CREATE: "/users",
    UPDATE: (id) => `/users/${id}`,
    DELETE: (id) => `/users/${id}`,
  },
  ADMINS: {
    LIST: "/admins",
    SEARCH: "/admins/search",
    DETAIL: (id) => `/admins/${id}`,
    CREATE: "/admins",
    UPDATE: (id) => `/admins/${id}`,
    DELETE: (id) => `/admins/${id}`,
  },
  SUPER_ADMIN: {
    RESET_PASSWORD_BY_DATE_RANGE: "/super-admin/reset-password-by-date-range",
    UPDATE_ADMIN_DIRECT: "/super-admin/update-admin-direct",
    CLEANUP_UNUSED_MEDIA_OLDER_THAN_30_DAYS:
      "/super-admin/cleanup-unused-media-older-than-30-days",
    GENERATE_MISSING_EXAM_SLUGS: "/super-admin/exams/generate-missing-slugs",
    REGENERATE_QUESTION_SLUGS: "/super-admin/questions/regenerate-slugs",
    BACKFILL_QUESTION_DEFAULT_POINTS:
      "/super-admin/questions/backfill-default-points",
    SEED_DEFAULT_TAGS: "/super-admin/tags/seed-defaults",
    SYNC_PERMISSIONS_FROM_CODES:
      "/super-admin/permissions/sync-from-codes",
    SYNC_SEO_MEDIA_SLOTS_FROM_PAGE_SLOTS:
      "/super-admin/seo-media/slots/sync-from-page-slots",
    PROMOTE_STUDENT_GRADE_BY_GRADUATION_YEAR:
      "/super-admin/students/promote-grade/by-graduation-year",
    UPDATE_STUDENT_GRADUATION_YEAR_BY_GRADE:
      "/super-admin/students/graduation-year/by-grade",
    HARD_DELETE_STUDENTS_BY_GRADUATION_YEAR_GRADE_EXCLUDED_COURSES:
      "/super-admin/students/hard-delete-by-graduation-year-grade-excluded-courses",
    AUTO_SUBMIT_EXPIRED_COMPETITION_ATTEMPTS:
      "/super-admin/competitions/auto-submit-expired-attempts",
  },
  STUDENTS: {
    LIST: "/students",
    SEARCH: "/students/search",
    STATS_BY_STATUS: "/students/stats/status",
    STATS_BY_GRADE: "/students/stats/grade",
    DETAIL: (id) => `/students/${id}`,
    CREATE: "/students",
    UPDATE: (id) => `/students/${id}`,
    DELETE: (id) => `/students/${id}`,
    EXPORT_LIST: "/students/export/excel",
  },
  SUBJECTS: {
    LIST: "/subjects",
    DETAIL: (id) => `/subjects/${id}`,
    CREATE: "/subjects",
    UPDATE: (id) => `/subjects/${id}`,
    DELETE: (id) => `/subjects/${id}`,
  },
  TAGS: {
    LIST: "/tags",
    DETAIL: (id) => `/tags/${id}`,
    CREATE: "/tags",
    UPDATE: (id) => `/tags/${id}`,
    DELETE: (id) => `/tags/${id}`,
  },
  DOCUMENTS: {
    LIST: "/documents",
    BY_SLUG: (slug) => `/documents/slug/${slug}`,
    DETAIL: (id) => `/documents/${id}`,
    CREATE: "/documents",
    UPDATE: (id) => `/documents/${id}`,
    DELETE: (id) => `/documents/${id}`,
  },
  TEACHER_PROFILES: {
    LIST: "/teacher-profiles",
    DETAIL: (id) => `/teacher-profiles/${id}`,
    CREATE: "/teacher-profiles",
    UPDATE: (id) => `/teacher-profiles/${id}`,
    DELETE: (id) => `/teacher-profiles/${id}`,
  },
  NEWS_ARTICLES: {
    LIST: '/news-articles',
    DETAIL: (id) => `/news-articles/${id}`,
    CREATE: '/news-articles',
    UPDATE: (id) => `/news-articles/${id}`,
    DELETE: (id) => `/news-articles/${id}`,
  },
  CHAPTERS: {
    LIST: "/chapters",
    SEARCH: "/chapters/search",
    DETAIL: (id) => `/chapters/${id}`,
    CREATE: "/chapters",
    UPDATE: (id) => `/chapters/${id}`,
    DELETE: (id) => `/chapters/${id}`,
  },
  PERMISSIONS: {
    LIST: "/permissions",
    GROUPS: "/permissions/groups",
    DETAIL: (id) => `/permissions/${id}`,
    CREATE: "/permissions",
    UPDATE: (id) => `/permissions/${id}`,
    DELETE: (id) => `/permissions/${id}`,
  },
  ROLES: {
    LIST: "/roles",
    DETAIL: (id) => `/roles/${id}`,
    CREATE: "/roles",
    UPDATE: (id) => `/roles/${id}`,
    DELETE: (id) => `/roles/${id}`,
    ASSIGN: "/roles/assign",
    REMOVE_FROM_USER: (userId, roleId) => `/roles/${userId}/roles/${roleId}`,
    USER_ROLES: (userId) => `/roles/user/${userId}`,
    TOGGLE_PERMISSION: (roleId, permissionId) => `/roles/${roleId}/permissions/${permissionId}/toggle`,
  },
  AUDIT_LOGS: {
    LIST: "/admin-audit-log",
    DETAIL: (id) => `/admin-audit-log/${id}`,
    ROLLBACK: (id) => `/admin-audit-log/rollback/${id}`,
  },
  MEDIA: {
    UPLOAD: '/media/upload',
    GET_PRESIGNED_UPLOAD_URL: '/media/upload/presigned',
    UPLOAD_COMPLETE: '/media/upload/complete',
    LIST: '/media',
    MY_LIST: '/media/my',
    BUCKETS: '/media/buckets',

    DETAIL: (id) => `/media/${id}`,
    UPDATE: (id) => `/media/${id}`,

    VIEW: (id) => `/media/${id}/view`,
    DOWNLOAD: (id) => `/media/${id}/download`,

    MY_VIEW: (id) => `/media/${id}/view/my`,
    MY_DOWNLOAD: (id) => `/media/${id}/download/my`,

    ADMIN_VIEW: (id) => `/media/admin/${id}/view`,
    ADMIN_DOWNLOAD: (id) => `/media/admin/${id}/download`,
    BATCH_MY_VIEW: '/media/batch/view/my',

    DELETE: (id) => `/media/${id}`,
    SOFT_DELETE_BY_USER: (id) => `/media/${id}/my`,
    HARD_DELETE: (id) => `/media/${id}/permanent`,
    BUCKET_STATISTICS: "/media/statistics/buckets",
    EXTRACT_TEXT: (id) => `/media/${id}/extract-text`,
    ADMIN_RAW_CONTENT: (id) => `/media/admin/${id}/raw-content`,
    MY_RAW_CONTENT: (id) => `/media/${id}/raw-content/my`,
  },
  SEO_MEDIA: {
    SLOTS: {
      CREATE: '/seo-media/slots',
      LIST: '/seo-media/slots',
      BY_CODE: (code) => `/seo-media/slots/code/${code}`,
      DETAIL: (slotId) => `/seo-media/slots/${slotId}`,
      UPDATE: (slotId) => `/seo-media/slots/${slotId}`,
      DELETE: (slotId) => `/seo-media/slots/${slotId}`,
      REORDER_ITEMS: (slotId) => `/seo-media/slots/${slotId}/items/reorder`,
    },
    ITEMS: {
      CREATE: '/seo-media/items',
      BY_SLOT: (slotId) => `/seo-media/slots/${slotId}/items`,
      UPDATE: (itemId) => `/seo-media/items/${itemId}`,
      DELETE: (itemId) => `/seo-media/items/${itemId}`,
    },
    UPLOAD_MEDIA: '/seo-media/upload-media',
    BUCKET_MEDIA: '/seo-media/bucket/media',
  },
  ACHIEVEMENT_BOARDS: {
    LIST: "/achievement-boards",
    CREATE: "/achievement-boards",
    DETAIL: (id) => `/achievement-boards/${id}`,
    UPDATE: (id) => `/achievement-boards/${id}`,
    DELETE: (id) => `/achievement-boards/${id}`,
    ROW_TEMPLATE: "/achievement-boards/rows/template",
    IMPORT_ROWS: (id) => `/achievement-boards/${id}/rows/import-excel`,
    UPDATE_ROW: (rowId) => `/achievement-boards/rows/${rowId}`,
    DELETE_ROW: (rowId) => `/achievement-boards/rows/${rowId}`,
    PUBLIC_SEO: "/achievement-boards/public/seo",
  },
  MEDIA_FOLDERS: {
    CREATE: "/media-folders",
    LIST: "/media-folders",
    ROOTS: "/media-folders/roots",
    DETAIL: (id) => `/media-folders/${id}`,
    CHILDREN: (id) => `/media-folders/${id}/children`,
    UPDATE: (id) => `/media-folders/${id}`,
    DELETE: (id) => `/media-folders/${id}`,
  },
  MEDIA_USAGES: {
    ATTACH: "/media-usages/attach",
    LIST: "/media-usages",
    BY_MEDIA: (mediaId) => `/media-usages/by-media/${mediaId}`,
    BY_ENTITY: (entityType, entityId) => `/media-usages/by-entity/${entityType}/${entityId}`,
    DELETE: (id) => `/media-usages/${id}`,
    DELETE_BY_ENTITY: (entityType, entityId) => `/media-usages/by-entity/${entityType}/${entityId}`,
  },
  COURSES: {
    LIST: "/courses",
    SEARCH: "/courses/search",
    MY_COURSES: "/courses/admin/my",
    DETAIL: (id) => `/courses/${id}`,
    CREATE: "/courses",
    UPDATE_BASIC_INFO: (id) => `/courses/${id}/basic-info`,
    UPDATE_PRICING: (id) => `/courses/${id}/pricing`,
    UPDATE_MEDIA: (id) => `/courses/${id}/media`,
    DELETE: (id) => `/courses/${id}`,
    STUDENTS_ATTENDANCE: (id) => `/courses/${id}/students-attendance`,
    STUDENTS_ATTENDANCE_EXPORT: (id) => `/courses/${id}/students-attendance/export`,
  },
  COURSE_CLASSES: {
    LIST: "/course-classes",
    SEARCH: "/course-classes/search",
    MY_CLASSES: "/course-classes/admin/my",
    DETAIL: (id) => `/course-classes/${id}`,
    CREATE: "/course-classes",
    UPDATE: (id) => `/course-classes/${id}`,
    DELETE: (id) => `/course-classes/${id}`,
  },
  COURSE_CLASS_LESSONS: {
    SWITCH: "/course-class-lessons/switch",
  },
  COURSE_ENROLLMENTS: {
    LIST: "/course-enrollments",
    DETAIL: (id) => `/course-enrollments/${id}`,
    CREATE: "/course-enrollments",
    UPDATE: (id) => `/course-enrollments/${id}`,
    DELETE: (id) => `/course-enrollments/${id}`,
    EXPORT_LIST: "/course-enrollments/export/excel",
  },
  CLASS_SESSIONS: {
    LIST: "/class-sessions",
    SEARCH: "/class-sessions/search",
    DETAIL: (id) => `/class-sessions/${id}`,
    CREATE: "/class-sessions",
    UPDATE: (id) => `/class-sessions/${id}`,
    DELETE: (id) => `/class-sessions/${id}`,
  },
  CLASS_STUDENTS: {
    LIST: "/class-students",
    DETAIL: (id) => `/class-students/${id}`,
    CREATE: "/class-students",
    DELETE: (classId, studentId) => `/class-students/${classId}/${studentId}`,
    EXPORT_EXCEL: "/class-students/export/excel",
  },
  ATTENDANCES: {
    LIST: "/attendances",
    DETAIL: (id) => `/attendances/${id}`,
    CREATE: "/attendances",
    CREATE_BULK_BY_SESSION: "/attendances/bulk/session",
    UPDATE: (id) => `/attendances/${id}`,
    DELETE: (id) => `/attendances/${id}`,
    STATISTICS_BY_SESSION: (sessionId) => `/attendances/statistics/session/${sessionId}`,
    EXPORT_BY_SESSION: (sessionId) => `/attendances/export/session/${sessionId}`,
    EXPORT_IMAGE: (id) => `/attendances/export/image/${id}`,
    TOGGLE_PARENT_NOTIFIED: (id) => `/attendances/${id}/toggle-parent-notified`,
    SEND_TO_PARENT: (id) => `/attendances/${id}/send-to-parent`,
  },
  STUDENT_POINT_LOGS: {
    BY_STUDENT: (studentId) => `/student-point-logs/students/${studentId}`,
    CREATE: "/student-point-logs",
    UPDATE: (pointLogId) => `/student-point-logs/${pointLogId}`,
    DELETE: (pointLogId) => `/student-point-logs/${pointLogId}`,
  },
  LEARNING_ITEMS: {
    LIST: "/learning-items",
    MY_ITEMS: "/learning-items/admin/my",
    DETAIL: (id) => `/learning-items/${id}`,
    CREATE: "/learning-items",
    UPDATE: (id) => `/learning-items/${id}`,
    DELETE: (id) => `/learning-items/${id}`,
  },
  LESSONS: {
    LIST: "/lessons",
    DETAIL: (id) => `/lessons/${id}`,
    CREATE: "/lessons",
    UPDATE: (id) => `/lessons/${id}`,
    DELETE: (id) => `/lessons/${id}`,
  },
  VIDEO_CONTENTS: {
    LIST: "/video-contents",
    DETAIL: (id) => `/video-contents/${id}`,
    CREATE: "/video-contents",
    UPDATE: (id) => `/video-contents/${id}`,
    DELETE: (id) => `/video-contents/${id}`,
  },
  DOCUMENT_CONTENTS: {
    LIST: "/document-contents",
    DETAIL: (id) => `/document-contents/${id}`,
    CREATE: "/document-contents",
    UPDATE: (id) => `/document-contents/${id}`,
    DELETE: (id) => `/document-contents/${id}`,
  },
  YOUTUBE_CONTENTS: {
    LIST: "/youtube-contents",
    DETAIL: (id) => `/youtube-contents/${id}`,
    CREATE: "/youtube-contents",
    UPDATE: (id) => `/youtube-contents/${id}`,
    DELETE: (id) => `/youtube-contents/${id}`,
  },
  HOMEWORK_CONTENTS: {
    LIST: "/homework-contents",
    DETAIL: (id) => `/homework-contents/${id}`,
    CREATE: "/homework-contents",
    UPDATE: (id) => `/homework-contents/${id}`,
    DELETE: (id) => `/homework-contents/${id}`,
    BY_COURSE: (courseId) => `/homework-contents/by-course/${courseId}`,
  },
  HOMEWORK_SUBMITS: {
    LIST: "/homework-submits",
    BY_STUDENT: (studentId) => `/homework-submits/student/${studentId}`,
    DETAIL: (id) => `/homework-submits/${id}`,
    CREATE: "/homework-submits",
    UPDATE: (id) => `/homework-submits/${id}`,
    FROM_COMPETITION: "/homework-submits/from-competition",
    COMPETITION_ATTEMPTS: (studentId) =>
      `/homework-submits/students/${studentId}/competition-attempts`,
    UPDATE_COMPETITION_SUBMIT: (id) =>
      `/homework-submits/${id}/competition-submit`,
    GRADE: (id) => `/homework-submits/${id}/grade`,
    DELETE: (id) => `/homework-submits/${id}`,
    ADMIN_DETAIL: (id) => `/admin/homework-submissions/${id}`,
    ADMIN_GRADE: (id) => `/admin/homework-submissions/${id}/grade`,
    ADMIN_UNGRADE: (id) => `/admin/homework-submissions/${id}/ungrade`,
    ADMIN_UPDATE_MEDIA_ALT: (homeworkSubmitId, mediaId) =>
      `/admin/homework-submissions/${homeworkSubmitId}/media/${mediaId}/alt`,
  },
  LESSON_LEARNING_ITEMS: {
    LIST: "/lesson-learning-items",
    DETAIL: (lessonId, learningItemId) => `/lesson-learning-items/${lessonId}/${learningItemId}`,
    CREATE: "/lesson-learning-items",
    DELETE: (lessonId, learningItemId) => `/lesson-learning-items/${lessonId}/${learningItemId}`,
    REORDER: "/lesson-learning-items/reorder",
  },
  NOTIFICATIONS: {
    MY: "/notifications/my",
    MY_STATS: "/notifications/my/stats",
    MARK_ALL_READ: "/notifications/my/mark-all-read",
    MARK_READ: (id) => `/notifications/${id}/mark-read`,
    DELETE: (id) => `/notifications/${id}`,
    BY_USER: (userId) => `/notifications/user/${userId}`,
    SEND: "/notifications/send",
  },
  TUITION_PAYMENT: {
    LIST: "/tuition-payments",
    DETAIL: (id) => `/tuition-payments/${id}`,
    CREATE: "/tuition-payments",
    CREATE_BULK: "/tuition-payments/bulk",
    CREATE_BULK_ARRAY: "/tuition-payments/bulk-array",
    UPDATE: (id) => `/tuition-payments/${id}`,
    CONFIRM_MANUAL_PAYMENT: (id) => `/tuition-payments/${id}/confirm-manual-payment`,
    MANUAL_RECONCILIATION: (id) => `/tuition-payments/${id}/manual-reconciliation`,
    UNRECONCILE_MANUAL_PAYMENT: (id) => `/tuition-payments/${id}/unreconcile-manual-payment`,
    UPDATE_BULK_ARRAY: "/tuition-payments/bulk-array",
    DELETE: (id) => `/tuition-payments/${id}`,
    STATS_BY_MONEY: "/tuition-payments/stats/money",
    STATS_BY_STATUS: "/tuition-payments/stats/status",
    STATS_MONTHLY: "/tuition-payments/stats/monthly",
    EXPORT_EXCEL_EXAMPLE: "/tuition-payments/export/excel/example",
    IMPORT_EXCEL_PREVIEW: "/tuition-payments/import/excel/preview",
    EXPORT_LIST: "/tuition-payments/export/excel",
  },
  ONLINE_COURSE_INVOICES: {
    ADMIN_LIST: "/online-course-invoices/admin",
    ADMIN_DETAIL: (invoiceId) => `/online-course-invoices/admin/${invoiceId}`,
    ADMIN_DELETE: (invoiceId) => `/online-course-invoices/admin/${invoiceId}`,
    CONFIRM_BANK_TRANSFER: (invoiceId) =>
      `/online-course-invoices/admin/${invoiceId}/confirm-bank-transfer`,
  },
  BANK_TRANSFER_TRANSACTIONS: {
    LIST: '/admin/bank-transfer-transactions',
    DETAIL: (id) => `/admin/bank-transfer-transactions/${id}`,
    FOR_TUITION_PAYMENT: (tuitionPaymentId) => `/admin/bank-transfer-transactions/tuition-payment/${tuitionPaymentId}`,
    STATISTICS: '/admin/bank-transfer-transactions/statistics',
    SYNC_SEPAY: '/admin/bank-transfer-transactions/sync-sepay',
  },
  PAYMENT_INTENTS: {
    CREATE_FOR_TUITION_PAYMENT: (tuitionPaymentId) => `/admin/payment-intents/tuition-payments/${tuitionPaymentId}`,
    CREATE_BULK: '/admin/payment-intents/tuition-payments/bulk',
  },
  RECEIVING_BANK_ACCOUNTS: {
    LIST: '/admin/receiving-bank-accounts',
    CREATE: '/admin/receiving-bank-accounts',
    UPDATE: (id) => `/admin/receiving-bank-accounts/${id}`,
    ACTIVATE: (id) => `/admin/receiving-bank-accounts/${id}/activate`,
    DEACTIVATE: (id) => `/admin/receiving-bank-accounts/${id}/deactivate`,
    SYNC_FROM_SEPAY: '/admin/receiving-bank-accounts/sync-from-sepay',
    SEPAY_BALANCE: (id) => `/admin/receiving-bank-accounts/${id}/sepay-balance`,
  },
  TUITION_COLLECTION_CONFIGURATION: {
    GET: '/admin/tuition-collection-configuration',
    UPDATE: '/admin/tuition-collection-configuration',
  },
  TUITION_GRADE_BANK_ACCOUNTS: {
    LIST: '/admin/tuition-grade-bank-accounts',
    UPDATE: '/admin/tuition-grade-bank-accounts',
  },
  BACKGROUND_JOBS: {
    LIST: '/admin/background-jobs',
    DETAIL: (id) => `/admin/background-jobs/${id}`,
    LOCKS: '/admin/background-job-locks',
    RUNS: '/admin/background-job-runs',
    RUN_DETAIL: (id) => `/admin/background-job-runs/${id}`,
    SEPAY_SYNC_CURSORS: '/admin/sepay-transaction-sync-cursors',
    SEPAY_SYNC_CURSOR: (scope) => `/admin/sepay-transaction-sync-cursors/${scope}`,
  },
  ASSISTANT_SHIFTS: {
    SERIES: '/assistant-shift-series',
    AVAILABLE_SERIES: '/assistant-shift-series/available',
    SERIES_DETAIL: (id) => `/assistant-shift-series/${id}`,
    SHIFTS: '/assistant-shifts',
    SHIFTS_BY_SERIES: (seriesId) => `/assistant-shifts/series/${seriesId}`,
    AVAILABLE_SHIFTS_BY_SERIES: (seriesId) => `/assistant-shifts/series/${seriesId}/available`,
    DETAIL: (id) => `/assistant-shifts/${id}`,
    ASSIGNMENTS: (shiftId) => `/assistant-shifts/${shiftId}/assignments`,
    ASSIGNMENT: (shiftId, adminId) => `/assistant-shifts/${shiftId}/assignments/${adminId}`,
    COPY_BY_SERIES: (seriesId) => `/assistant-shifts/series/${seriesId}/copy`,
    LOCK_BY_SERIES: (seriesId) => `/assistant-shifts/series/${seriesId}/lock`,
    UNLOCK_BY_SERIES: (seriesId) => `/assistant-shifts/series/${seriesId}/unlock`,
    SELF_REGISTRATION_WINDOW: (seriesId) => `/assistant-shifts/series/${seriesId}/self-registration-window`,
    REGISTER: (id) => `/assistant-shifts/${id}/register`,
    MY_SCHEDULE: '/assistant-shifts/my',
    MY_MONTHLY_STATISTICS: '/assistant-shifts/my/monthly-statistics',
  },
  EXAM_IMPORT_SESSION: {
    LIST: "/exam-import-sessions",
    DETAIL: (sessionId) => `/exam-import-sessions/${sessionId}`,
    CREATE: "/exam-import-sessions",
    MY_RAW_CONTENT: (sessionId) => `/exam-import-sessions/${sessionId}/raw-content/my`,
    UPDATE_MY_RAW_CONTENT: (sessionId) => `/exam-import-sessions/${sessionId}/raw-content/my`,
    SPLIT_FROM_SESSION: (sessionId) => `/exam-import-sessions/${sessionId}/split-questions/my`,
    SPLIT_FROM_RAW_CONTENT: (sessionId) => `/exam-import-sessions/${sessionId}/split-question/raw-content`,
    CLASSIFY_CHAPTERS: (sessionId) => `/exam-import-sessions/${sessionId}/classify-chapters/my`,
    MIGRATE: (sessionId) => `/exam-import-sessions/${sessionId}/migrate/my`,
    MANUAL_SPLIT: (sessionId) => `/exam-import-sessions/${sessionId}/manual-split/my`,
  },
  TEMP_EXAM: {
    BY_SESSION: (sessionId) => `/temp-exams/session/${sessionId}`,
    CREATE: (sessionId) => `/temp-exams/session/${sessionId}`,
    UPDATE: (tempExamId) => `/temp-exams/${tempExamId}`,
  },
  TEMP_SECTION: {
    BY_SESSION: (sessionId) => `/temp-sections/session/${sessionId}`,
    BY_ID: (tempSectionId) => `/temp-sections/${tempSectionId}`,
    CREATE: (sessionId) => `/temp-sections/session/${sessionId}`,
    UPDATE: (tempSectionId) => `/temp-sections/${tempSectionId}`,
    DELETE: (tempSectionId) => `/temp-sections/${tempSectionId}`,
    REORDER: '/temp-sections/reorder',
  },
  TEMP_QUESTION: {
    BY_SESSION: (sessionId) => `/temp-questions/session/${sessionId}`,
    BY_ID: (tempQuestionId) => `/temp-questions/${tempQuestionId}`,
    CREATE: (sessionId) => `/temp-questions/session/${sessionId}`,
    UPDATE: (tempQuestionId) => `/temp-questions/${tempQuestionId}`,
    DELETE: (tempQuestionId) => `/temp-questions/${tempQuestionId}`,
    REORDER: '/temp-questions/reorder',
    LINK_SECTION: (tempQuestionId) => `/temp-questions/${tempQuestionId}/link-section`,
    UPDATE_SECTION_POINTS: (tempSectionId) => `/temp-questions/section/${tempSectionId}/points`,
  },
  TEMP_STATEMENT: {
    CREATE: (tempQuestionId) => `/temp-statements/question/${tempQuestionId}`,
    UPDATE: (tempStatementId) => `/temp-statements/${tempStatementId}`,
    DELETE: (tempStatementId) => `/temp-statements/${tempStatementId}`,
    REORDER: '/temp-statements/reorder',
  },
  QUESTIONS: {
    LIST: "/questions",
    MY_QUESTIONS: "/questions/my-questions",
    SEARCH: "/questions/search",
    DETAIL: (id) => `/questions/${id}`,
    CREATE: "/questions",
    UPDATE: (id) => `/questions/${id}`,
    DELETE: (id) => `/questions/${id}`,
    BY_EXAM: (examId) => `/exams/${examId}/questions`,
    REORDER: "/questions/reorder",
    ADD_TO_EXAM: "/questions/exam",
    REMOVE_FROM_EXAM: "/questions/exam",
    ADD_TO_SECTION: "/questions/section",
  },
  STATEMENTS: {
    CREATE: (questionId) => `/statements/question/${questionId}`,
    UPDATE: (id) => `/statements/${id}`,
    DELETE: (id) => `/statements/${id}`,
  },
  EXAMS: {
    LIST: "/exams",
    MY_EXAMS: "/exams/my-exams",
    SEARCH: "/exams/search",
    DETAIL: (id) => `/exams/${id}`,
    CREATE: "/exams",
    UPDATE: (id) => `/exams/${id}`,
    DELETE: (id) => `/exams/${id}`,
    SECTIONS: (examId) => `/exams/${examId}/sections`,
  },
  COMPETITIONS: {
    LIST: "/competitions",
    MY_COMPETITIONS: "/competitions/my-competitions",
    SEARCH: "/competitions/search",
    DETAIL: (id) => `/competitions/${id}`,
    CREATE: "/competitions",
    UPDATE: (id) => `/competitions/${id}`,
    DELETE: (id) => `/competitions/${id}`,
    QUESTION_STATS: (id) => `/competitions/${id}/question-stats`,
  },
  COMPETITION_SUBMITS: {
    LIST: "/competition-submits",
    BY_STUDENT: (studentId) => `/competition-submits/student/${studentId}`,
    DETAIL: (id) => `/competition-submits/${id}`,
    UPDATE: (id) => `/competition-submits/${id}`,
    FULL_DETAIL: (id) => `/competition-submits/${id}/detail`,
    REGRADE: (id) => `/competition-submits/${id}/regrade`,
    DELETE: (id) => `/competition-submits/${id}`,
    EXPORT_EXCEL: "/competition-submits/export/excel",
  },
  SECTIONS: {
    LIST: "/sections",
    DETAIL: (id) => `/sections/${id}`,
    CREATE: "/sections",
    UPDATE: (id) => `/sections/${id}`,
    DELETE: (id) => `/sections/${id}`,
    BY_EXAM: (examId) => `/sections?examId=${examId}`,
  },
  MARKDOWN: {
    FIX_SPELLING: '/markdown/fix-spelling',
  },
};

// HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export * from "./visibility"
export * from "./exam-constants"
export * from "./options"
export * from "./permission/permission.codes"
