// API Base URL
export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:3001/api";

// Storage Keys
export const STORAGE_KEYS = {
  ACCESS_TOKEN: "access_token",
  REFRESH_TOKEN: "refresh_token",
  USER_INFO: "user_info",
  USER: "user",
};

// Routes
export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  PROFILE_INFO: "/profile/info",
  PROFILE_PERMISSIONS: "/profile/permissions",
  PROFILE_SECURITY: "/profile/security",
  SETTINGS: "/settings",
  NOT_FOUND: '/404',
  LOADING_REDIRECT: '/loading',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: (id) => `/roles/${id}/edit`,
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  PERMISSIONS_EDIT: (id) => `/permissions/${id}/edit`,
  AUDIT_LOGS: '/audit-logs',
  MEDIA: '/media',
  MEDIA_FOLDERS: '/media-folders',
  ADMINS: '/admins',
  ADMIN_DETAIL: (id = ':id') => `/admins/${id}`,
  ADMIN_ROLES: (id = ':id') => `/admins/${id}/roles`,
  ADMIN_MEDIA: (id = ':id') => `/admins/${id}/media`,
  ADMIN_AUDIT_LOGS: (id = ':id') => `/admins/${id}/audit-logs`,
  STUDENTS: '/students',
  STUDENT_DETAIL: (id = ':id') => `/students/${id}`,
  STUDENT_ROLES: (id = ':id') => `/students/${id}/roles`,
  STUDENT_MEDIA: (id = ':id') => `/students/${id}/media`,
  STUDENT_CLASSES: (id = ':id') => `/students/${id}/classes`,
  STUDENT_COURSES: (id = ':id') => `/students/${id}/courses`,
  STUDENT_ATTENDANCE: (id = ':id') => `/students/${id}/attendance`,
  SUBJECTS: '/subjects',
  SUBJECT_DETAIL: (id = ':id') => `/subjects/${id}`,
  CHAPTERS: '/chapters',
  CHAPTER_DETAIL: (id = ':id') => `/chapters/${id}`,
  COURSES: '/courses',
  MY_COURSES: '/my-courses',
  COURSE_DETAIL: (id = ':id') => `/courses/${id}`,
  COURSE_CLASSES: (id = ':id') => `/courses/${id}/classes`,
  COURSE_STUDENTS: (id = ':id') => `/courses/${id}/students`,
  COURSE_LESSONS: (id = ':id') => `/courses/${id}/lessons`,
  CLASSES: '/classes',
  MY_CLASSES: '/my-classes',
  CLASS_DETAIL: (id = ':id') => `/classes/${id}`,
  CLASS_STUDENTS: (id = ':id') => `/classes/${id}/students`,
  CLASS_SESSIONS: (id = ':id') => `/classes/${id}/sessions`,
  CLASS_SCHEDULE: (id = ':id') => `/classes/${id}/schedule`,
  CLASS_ATTENDANCE: (id = ':id') => `/classes/${id}/attendance`,
};

// API Endpoints
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/admin/login",
    REGISTER: "/auth/admin/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/admin/me",
  },
  PROFILE: {
    GET: "admin/profile",
    UPDATE: "admin/profile",
  },
  USERS: {
    LIST: "/users",
    DETAIL: (id) => `/users/${id}`,
    TOGGLE_ACTIVATION: (id) => `/users/${id}/toggle-activation`,
    CREATE: "/users",
    UPDATE: (id) => `/users/${id}`,
    DELETE: (id) => `/users/${id}`,
  },
  ADMINS: {
    LIST: "/admins",
    DETAIL: (id) => `/admins/${id}`,
    CREATE: "/admins",
    UPDATE: (id) => `/admins/${id}`,
    DELETE: (id) => `/admins/${id}`,
  },
  STUDENTS: {
    LIST: "/students",
    DETAIL: (id) => `/students/${id}`,
    CREATE: "/students",
    UPDATE: (id) => `/students/${id}`,
    DELETE: (id) => `/students/${id}`,
  },
  SUBJECTS: {
    LIST: "/subjects",
    DETAIL: (id) => `/subjects/${id}`,
    CREATE: "/subjects",
    UPDATE: (id) => `/subjects/${id}`,
    DELETE: (id) => `/subjects/${id}`,
  },
  CHAPTERS: {
    LIST: "/chapters",
    DETAIL: (id) => `/chapters/${id}`,
    CREATE: "/chapters",
    UPDATE: (id) => `/chapters/${id}`,
    DELETE: (id) => `/chapters/${id}`,
  },
  PERMISSIONS: {
    LIST: "/permissions",
    GROUPS: "/permissions/groups",
    DETAIL: (id) => `/permissions/${id}`,
    CREATE: "/permissions",
    UPDATE: (id) => `/permissions/${id}`,
    DELETE: (id) => `/permissions/${id}`,
  },
  ROLES: {
    LIST: "/roles",
    DETAIL: (id) => `/roles/${id}`,
    CREATE: "/roles",
    UPDATE: (id) => `/roles/${id}`,
    DELETE: (id) => `/roles/${id}`,
    ASSIGN: "/roles/assign",
    REMOVE_FROM_USER: (userId, roleId) => `/roles/${userId}/roles/${roleId}`,
    USER_ROLES: (userId) => `/roles/user/${userId}`,
    TOGGLE_PERMISSION: (roleId, permissionId) => `/roles/${roleId}/permissions/${permissionId}/toggle`,
  },
  AUDIT_LOGS: {
    LIST: "/admin-audit-log",
    DETAIL: (id) => `/admin-audit-log/${id}`,
    ROLLBACK: (id) => `/admin-audit-log/rollback/${id}`,
  },
  MEDIA: {
    UPLOAD: "/media/upload",
    LIST: "/media",
    DETAIL: (id) => `/media/${id}`,
    DOWNLOAD: (id) => `/media/${id}/download`,
    VIEW: (id) => `/media/${id}/view`,
    UPDATE: (id) => `/media/${id}`,
    DELETE: (id) => `/media/${id}`,
    HARD_DELETE: (id) => `/media/${id}/permanent`,
  },
  MEDIA_FOLDERS: {
    CREATE: "/media-folders",
    LIST: "/media-folders",
    ROOTS: "/media-folders/roots",
    DETAIL: (id) => `/media-folders/${id}`,
    CHILDREN: (id) => `/media-folders/${id}/children`,
    UPDATE: (id) => `/media-folders/${id}`,
    DELETE: (id) => `/media-folders/${id}`,
  },
  MEDIA_USAGES: {
    ATTACH: "/media-usages/attach",
    LIST: "/media-usages",
    BY_MEDIA: (mediaId) => `/media-usages/by-media/${mediaId}`,
    BY_ENTITY: (entityType, entityId) => `/media-usages/by-entity/${entityType}/${entityId}`,
    DELETE: (id) => `/media-usages/${id}`,
    DELETE_BY_ENTITY: (entityType, entityId) => `/media-usages/by-entity/${entityType}/${entityId}`,
  },
  COURSES: {
    LIST: "/courses",
    DETAIL: (id) => `/courses/${id}`,
    CREATE: "/courses",
    UPDATE: (id) => `/courses/${id}`,
    DELETE: (id) => `/courses/${id}`,
  },
  COURSE_CLASSES: {
    LIST: "/course-classes",
    DETAIL: (id) => `/course-classes/${id}`,
    CREATE: "/course-classes",
    UPDATE: (id) => `/course-classes/${id}`,
    DELETE: (id) => `/course-classes/${id}`,
  },
  COURSE_ENROLLMENTS: {
    LIST: "/course-enrollments",
    DETAIL: (id) => `/course-enrollments/${id}`,
    CREATE: "/course-enrollments",
    UPDATE: (id) => `/course-enrollments/${id}`,
    DELETE: (id) => `/course-enrollments/${id}`,
  },
  CLASS_SESSIONS: {
    LIST: "/class-sessions",
    DETAIL: (id) => `/class-sessions/${id}`,
    CREATE: "/class-sessions",
    UPDATE: (id) => `/class-sessions/${id}`,
    DELETE: (id) => `/class-sessions/${id}`,
  },
  CLASS_STUDENTS: {
    LIST: "/class-students",
    DETAIL: (id) => `/class-students/${id}`,
    CREATE: "/class-students",
    DELETE: (classId, studentId) => `/class-students/${classId}/${studentId}`,
  },
  ATTENDANCES: {
    LIST: "/attendances",
    DETAIL: (id) => `/attendances/${id}`,
    CREATE: "/attendances",
    CREATE_BULK_BY_SESSION: "/attendances/bulk/session",
    UPDATE: (id) => `/attendances/${id}`,
    DELETE: (id) => `/attendances/${id}`,
    STATISTICS_BY_SESSION: (sessionId) => `/attendances/statistics/session/${sessionId}`,
    EXPORT_BY_SESSION: (sessionId) => `/attendances/export/session/${sessionId}`,
  },
};

// HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export * from "./visibility"