// API Base URL
export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:3001/api";

// Storage Keys
export const STORAGE_KEYS = {
  ACCESS_TOKEN: "access_token",
  REFRESH_TOKEN: "refresh_token",
  USER_INFO: "user_info",
  USER: "user",
  SIDEBAR_OPEN: "sidebar_open",
};

// Routes
export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  PROFILE_INFO: "/profile/info",
  PROFILE_PERMISSIONS: "/profile/permissions",
  PROFILE_SECURITY: "/profile/security",
  SETTINGS: "/settings",
  NOT_FOUND: '/404',
  LOADING_REDIRECT: '/loading',
  ROLES: '/roles',
  ROLES_CREATE: '/roles/create',
  ROLES_EDIT: (id) => `/roles/${id}/edit`,
  PERMISSIONS: '/permissions',
  PERMISSIONS_CREATE: '/permissions/create',
  PERMISSIONS_EDIT: (id) => `/permissions/${id}/edit`,
  AUDIT_LOGS: '/audit-logs',
  MEDIA: '/media',
  MEDIA_FOLDERS: '/media-folders',
  ADMINS: '/admins',
  ADMIN_DETAIL: (id = ':id') => `/admins/${id}`,
  ADMIN_ROLES: (id = ':id') => `/admins/${id}/roles`,
  ADMIN_MEDIA: (id = ':id') => `/admins/${id}/media`,
  ADMIN_AUDIT_LOGS: (id = ':id') => `/admins/${id}/audit-logs`,
  STUDENTS: '/students',
  STUDENT_DETAIL: (id = ':id') => `/students/${id}`,
  STUDENT_ROLES: (id = ':id') => `/students/${id}/roles`,
  STUDENT_MEDIA: (id = ':id') => `/students/${id}/media`,
  STUDENT_CLASSES: (id = ':id') => `/students/${id}/classes`,
  STUDENT_COURSES: (id = ':id') => `/students/${id}/courses`,
  STUDENT_ATTENDANCE: (id = ':id') => `/students/${id}/attendance`,
  SUBJECTS: '/subjects',
  SUBJECT_DETAIL: (id = ':id') => `/subjects/${id}`,
  CHAPTERS: '/chapters',
  CHAPTER_DETAIL: (id = ':id') => `/chapters/${id}`,
  COURSES: '/courses',
  MY_COURSES: '/my-courses',
  COURSE_DETAIL: (id = ':id') => `/courses/${id}`,
  COURSE_PRICING: (id = ':id') => `/courses/${id}/pricing`,
  COURSE_CLASSES: (id = ':id') => `/courses/${id}/classes`,
  COURSE_STUDENTS: (id = ':id') => `/courses/${id}/students`,
  COURSE_ATTENDANCE: (id = ':id') => `/courses/${id}/attendance`,
  COURSE_LESSONS: (id = ':id') => `/courses/${id}/lessons`,
  CLASSES: '/classes',
  MY_CLASSES: '/my-classes',
  CLASS_DETAIL: (id = ':id') => `/classes/${id}`,
  CLASS_STUDENTS: (id = ':id') => `/classes/${id}/students`,
  CLASS_SESSIONS: (id = ':id') => `/classes/${id}/sessions`,
  CLASS_SCHEDULE: (id = ':id') => `/classes/${id}/schedule`,
  CLASS_ATTENDANCE: (id = ':id') => `/classes/${id}/attendance`,
  CLASS_NOTIFICATIONS: (id = ':id') => `/classes/${id}/notifications`,
  BROADCAST_NOTIFICATIONS: '/notifications/broadcast',
  NOTIFICATION_LOGS: '/notifications/logs',
  TUITION_PAYMENTS: '/tuition-payments',
  EXAM_IMPORT_SESSIONS: '/exam-import-sessions',
  EXAM_IMPORT_SESSION_DETAIL: (id = ':id') => `/exam-import-sessions/${id}`,
  EXAM_IMPORT_SESSION_UPLOAD: (id = ':id') => `/exam-import-sessions/${id}/upload`,
  EXAM_IMPORT_SESSION_PROCESS: (id = ':id') => `/exam-import-sessions/${id}/process`,
  EXAM_IMPORT_SESSION_PREVIEW: (id = ':id') => `/exam-import-sessions/${id}/preview`,
  QUESTIONS: '/questions',
  EXAMS: '/exams',
  EXAM_DETAIL: (id = ':id') => `/exams/${id}`,
  EXAM_QUESTIONS: (id = ':id') => `/exams/${id}/questions`,
  EXAM_PREVIEW: (id = ':id') => `/exams/${id}/preview`,
};

// API Endpoints
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/admin/login",
    REGISTER: "/auth/admin/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/admin/me",
  },
  PROFILE: {
    GET: "admin/profile",
    UPDATE: "admin/profile",
  },
  USERS: {
    LIST: "/users",
    DETAIL: (id) => `/users/${id}`,
    TOGGLE_ACTIVATION: (id) => `/users/${id}/toggle-activation`,
    CREATE: "/users",
    UPDATE: (id) => `/users/${id}`,
    DELETE: (id) => `/users/${id}`,
  },
  ADMINS: {
    LIST: "/admins",
    DETAIL: (id) => `/admins/${id}`,
    CREATE: "/admins",
    UPDATE: (id) => `/admins/${id}`,
    DELETE: (id) => `/admins/${id}`,
  },
  STUDENTS: {
    LIST: "/students",
    STATS_BY_STATUS: "/students/stats/status",
    STATS_BY_GRADE: "/students/stats/grade",
    DETAIL: (id) => `/students/${id}`,
    CREATE: "/students",
    UPDATE: (id) => `/students/${id}`,
    DELETE: (id) => `/students/${id}`,
    EXPORT_LIST: "/students/export/excel",
  },
  SUBJECTS: {
    LIST: "/subjects",
    DETAIL: (id) => `/subjects/${id}`,
    CREATE: "/subjects",
    UPDATE: (id) => `/subjects/${id}`,
    DELETE: (id) => `/subjects/${id}`,
  },
  CHAPTERS: {
    LIST: "/chapters",
    SEARCH: "/chapters/search",
    DETAIL: (id) => `/chapters/${id}`,
    CREATE: "/chapters",
    UPDATE: (id) => `/chapters/${id}`,
    DELETE: (id) => `/chapters/${id}`,
  },
  PERMISSIONS: {
    LIST: "/permissions",
    GROUPS: "/permissions/groups",
    DETAIL: (id) => `/permissions/${id}`,
    CREATE: "/permissions",
    UPDATE: (id) => `/permissions/${id}`,
    DELETE: (id) => `/permissions/${id}`,
  },
  ROLES: {
    LIST: "/roles",
    DETAIL: (id) => `/roles/${id}`,
    CREATE: "/roles",
    UPDATE: (id) => `/roles/${id}`,
    DELETE: (id) => `/roles/${id}`,
    ASSIGN: "/roles/assign",
    REMOVE_FROM_USER: (userId, roleId) => `/roles/${userId}/roles/${roleId}`,
    USER_ROLES: (userId) => `/roles/user/${userId}`,
    TOGGLE_PERMISSION: (roleId, permissionId) => `/roles/${roleId}/permissions/${permissionId}/toggle`,
  },
  AUDIT_LOGS: {
    LIST: "/admin-audit-log",
    DETAIL: (id) => `/admin-audit-log/${id}`,
    ROLLBACK: (id) => `/admin-audit-log/rollback/${id}`,
  },
  MEDIA: {
    UPLOAD: '/media/upload',
    GET_PRESIGNED_UPLOAD_URL: '/media/upload/presigned',
    UPLOAD_COMPLETE: '/media/upload/complete',
    LIST: '/media',
    MY_LIST: '/media/my',
    BUCKETS: '/media/buckets',

    DETAIL: (id) => `/media/${id}`,
    UPDATE: (id) => `/media/${id}`,

    VIEW: (id) => `/media/${id}/view`,
    DOWNLOAD: (id) => `/media/${id}/download`,

    MY_VIEW: (id) => `/media/${id}/view/my`,
    MY_DOWNLOAD: (id) => `/media/${id}/download/my`,

    ADMIN_VIEW: (id) => `/media/admin/${id}/view`,
    ADMIN_DOWNLOAD: (id) => `/media/admin/${id}/download`,
    BATCH_MY_VIEW: '/media/batch/view/my',

    DELETE: (id) => `/media/${id}`,
    SOFT_DELETE_BY_USER: (id) => `/media/${id}/my`,
    HARD_DELETE: (id) => `/media/${id}/permanent`,
    BUCKET_STATISTICS: "/media/statistics/buckets",
    EXTRACT_TEXT: (id) => `/media/${id}/extract-text`,
    ADMIN_RAW_CONTENT: (id) => `/media/admin/${id}/raw-content`,
    MY_RAW_CONTENT: (id) => `/media/${id}/raw-content/my`,
  },
  MEDIA_FOLDERS: {
    CREATE: "/media-folders",
    LIST: "/media-folders",
    ROOTS: "/media-folders/roots",
    DETAIL: (id) => `/media-folders/${id}`,
    CHILDREN: (id) => `/media-folders/${id}/children`,
    UPDATE: (id) => `/media-folders/${id}`,
    DELETE: (id) => `/media-folders/${id}`,
  },
  MEDIA_USAGES: {
    ATTACH: "/media-usages/attach",
    LIST: "/media-usages",
    BY_MEDIA: (mediaId) => `/media-usages/by-media/${mediaId}`,
    BY_ENTITY: (entityType, entityId) => `/media-usages/by-entity/${entityType}/${entityId}`,
    DELETE: (id) => `/media-usages/${id}`,
    DELETE_BY_ENTITY: (entityType, entityId) => `/media-usages/by-entity/${entityType}/${entityId}`,
  },
  COURSES: {
    LIST: "/courses",
    SEARCH: "/courses/search",
    MY_COURSES: "/courses/admin/my",
    DETAIL: (id) => `/courses/${id}`,
    CREATE: "/courses",
    UPDATE_BASIC_INFO: (id) => `/courses/${id}/basic-info`,
    UPDATE_PRICING: (id) => `/courses/${id}/pricing`,
    DELETE: (id) => `/courses/${id}`,
    STUDENTS_ATTENDANCE: (id) => `/courses/${id}/students-attendance`,
    STUDENTS_ATTENDANCE_EXPORT: (id) => `/courses/${id}/students-attendance/export`,
  },
  COURSE_CLASSES: {
    LIST: "/course-classes",
    SEARCH: "/course-classes/search",
    MY_CLASSES: "/course-classes/admin/my",
    DETAIL: (id) => `/course-classes/${id}`,
    CREATE: "/course-classes",
    UPDATE: (id) => `/course-classes/${id}`,
    DELETE: (id) => `/course-classes/${id}`,
  },
  COURSE_ENROLLMENTS: {
    LIST: "/course-enrollments",
    DETAIL: (id) => `/course-enrollments/${id}`,
    CREATE: "/course-enrollments",
    UPDATE: (id) => `/course-enrollments/${id}`,
    DELETE: (id) => `/course-enrollments/${id}`,
  },
  CLASS_SESSIONS: {
    LIST: "/class-sessions",
    SEARCH: "/class-sessions/search",
    DETAIL: (id) => `/class-sessions/${id}`,
    CREATE: "/class-sessions",
    UPDATE: (id) => `/class-sessions/${id}`,
    DELETE: (id) => `/class-sessions/${id}`,
  },
  CLASS_STUDENTS: {
    LIST: "/class-students",
    DETAIL: (id) => `/class-students/${id}`,
    CREATE: "/class-students",
    DELETE: (classId, studentId) => `/class-students/${classId}/${studentId}`,
  },
  ATTENDANCES: {
    LIST: "/attendances",
    DETAIL: (id) => `/attendances/${id}`,
    CREATE: "/attendances",
    CREATE_BULK_BY_SESSION: "/attendances/bulk/session",
    UPDATE: (id) => `/attendances/${id}`,
    DELETE: (id) => `/attendances/${id}`,
    STATISTICS_BY_SESSION: (sessionId) => `/attendances/statistics/session/${sessionId}`,
    EXPORT_BY_SESSION: (sessionId) => `/attendances/export/session/${sessionId}`,
    EXPORT_IMAGE: (id) => `/attendances/export/image/${id}`,
  },
  LEARNING_ITEMS: {
    LIST: "/learning-items",
    MY_ITEMS: "/learning-items/admin/my",
    DETAIL: (id) => `/learning-items/${id}`,
    CREATE: "/learning-items",
    UPDATE: (id) => `/learning-items/${id}`,
    DELETE: (id) => `/learning-items/${id}`,
  },
  LESSONS: {
    LIST: "/lessons",
    DETAIL: (id) => `/lessons/${id}`,
    CREATE: "/lessons",
    UPDATE: (id) => `/lessons/${id}`,
    DELETE: (id) => `/lessons/${id}`,
  },
  VIDEO_CONTENTS: {
    LIST: "/video-contents",
    DETAIL: (id) => `/video-contents/${id}`,
    CREATE: "/video-contents",
    UPDATE: (id) => `/video-contents/${id}`,
    DELETE: (id) => `/video-contents/${id}`,
  },
  YOUTUBE_CONTENTS: {
    LIST: "/youtube-contents",
    DETAIL: (id) => `/youtube-contents/${id}`,
    CREATE: "/youtube-contents",
    UPDATE: (id) => `/youtube-contents/${id}`,
    DELETE: (id) => `/youtube-contents/${id}`,
  },
  HOMEWORK_CONTENTS: {
    LIST: "/homework-contents",
    DETAIL: (id) => `/homework-contents/${id}`,
    CREATE: "/homework-contents",
    UPDATE: (id) => `/homework-contents/${id}`,
    DELETE: (id) => `/homework-contents/${id}`,
  },
  HOMEWORK_SUBMITS: {
    LIST: "/homework-submits",
    DETAIL: (id) => `/homework-submits/${id}`,
    CREATE: "/homework-submits",
    UPDATE: (id) => `/homework-submits/${id}`,
    GRADE: (id) => `/homework-submits/${id}/grade`,
    DELETE: (id) => `/homework-submits/${id}`,
  },
  LESSON_LEARNING_ITEMS: {
    LIST: "/lesson-learning-items",
    DETAIL: (lessonId, learningItemId) => `/lesson-learning-items/${lessonId}/${learningItemId}`,
    CREATE: "/lesson-learning-items",
    DELETE: (lessonId, learningItemId) => `/lesson-learning-items/${lessonId}/${learningItemId}`,
  },
  NOTIFICATIONS: {
    MY: "/notifications/my",
    MY_STATS: "/notifications/my/stats",
    MARK_ALL_READ: "/notifications/my/mark-all-read",
    MARK_READ: (id) => `/notifications/${id}/mark-read`,
    DELETE: (id) => `/notifications/${id}`,
    BY_USER: (userId) => `/notifications/user/${userId}`,
    SEND: "/notifications/send",
  },
  TUITION_PAYMENT: {
    LIST: "/tuition-payments",
    DETAIL: (id) => `/tuition-payments/${id}`,
    CREATE: "/tuition-payments",
    CREATE_BULK: "/tuition-payments/bulk",
    CREATE_BULK_ARRAY: "/tuition-payments/bulk-array",
    UPDATE: (id) => `/tuition-payments/${id}`,
    UPDATE_BULK_ARRAY: "/tuition-payments/bulk-array",
    DELETE: (id) => `/tuition-payments/${id}`,
    STATS_BY_MONEY: "/tuition-payments/stats/money",
    STATS_BY_STATUS: "/tuition-payments/stats/status",
    STATS_MONTHLY: "/tuition-payments/stats/monthly",
    EXPORT_EXCEL_EXAMPLE: "/tuition-payments/export/excel/example",
    IMPORT_EXCEL_PREVIEW: "/tuition-payments/import/excel/preview",
    EXPORT_LIST: "/tuition-payments/export/excel",
  },
  EXAM_IMPORT_SESSION: {
    LIST: "/exam-import-sessions",
    DETAIL: (sessionId) => `/exam-import-sessions/${sessionId}`,
    CREATE: "/exam-import-sessions",
    MY_RAW_CONTENT: (sessionId) => `/exam-import-sessions/${sessionId}/raw-content/my`,
    UPDATE_MY_RAW_CONTENT: (sessionId) => `/exam-import-sessions/${sessionId}/raw-content/my`,
    SPLIT_FROM_SESSION: (sessionId) => `/exam-import-sessions/${sessionId}/split-questions/my`,
    SPLIT_FROM_RAW_CONTENT: (sessionId) => `/exam-import-sessions/${sessionId}/split-question/raw-content`,
    CLASSIFY_CHAPTERS: (sessionId) => `/exam-import-sessions/${sessionId}/classify-chapters/my`,
    MIGRATE: (sessionId) => `/exam-import-sessions/${sessionId}/migrate/my`,
  },
  TEMP_EXAM: {
    BY_SESSION: (sessionId) => `/temp-exams/session/${sessionId}`,
    CREATE: (sessionId) => `/temp-exams/session/${sessionId}`,
    UPDATE: (tempExamId) => `/temp-exams/${tempExamId}`,
  },
  TEMP_SECTION: {
    BY_SESSION: (sessionId) => `/temp-sections/session/${sessionId}`,
    BY_ID: (tempSectionId) => `/temp-sections/${tempSectionId}`,
    CREATE: (sessionId) => `/temp-sections/session/${sessionId}`,
    UPDATE: (tempSectionId) => `/temp-sections/${tempSectionId}`,
    DELETE: (tempSectionId) => `/temp-sections/${tempSectionId}`,
    REORDER: '/temp-sections/reorder',
  },
  TEMP_QUESTION: {
    BY_SESSION: (sessionId) => `/temp-questions/session/${sessionId}`,
    BY_ID: (tempQuestionId) => `/temp-questions/${tempQuestionId}`,
    CREATE: (sessionId) => `/temp-questions/session/${sessionId}`,
    UPDATE: (tempQuestionId) => `/temp-questions/${tempQuestionId}`,
    DELETE: (tempQuestionId) => `/temp-questions/${tempQuestionId}`,
    REORDER: '/temp-questions/reorder',
    LINK_SECTION: (tempQuestionId) => `/temp-questions/${tempQuestionId}/link-section`,
  },
  TEMP_STATEMENT: {
    CREATE: (tempQuestionId) => `/temp-statements/question/${tempQuestionId}`,
    UPDATE: (tempStatementId) => `/temp-statements/${tempStatementId}`,
    DELETE: (tempStatementId) => `/temp-statements/${tempStatementId}`,
    REORDER: '/temp-statements/reorder',
  },
  QUESTIONS: {
    LIST: "/questions",
    DETAIL: (id) => `/questions/${id}`,
    CREATE: "/questions",
    UPDATE: (id) => `/questions/${id}`,
    DELETE: (id) => `/questions/${id}`,
    BY_EXAM: (examId) => `/exams/${examId}/questions`,
  },
  STATEMENTS: {
    CREATE: (questionId) => `/statements/question/${questionId}`,
    UPDATE: (id) => `/statements/${id}`,
    DELETE: (id) => `/statements/${id}`,
  },
  EXAMS: {
    LIST: "/exams",
    DETAIL: (id) => `/exams/${id}`,
    CREATE: "/exams",
    UPDATE: (id) => `/exams/${id}`,
    DELETE: (id) => `/exams/${id}`,
    SECTIONS: (examId) => `/exams/${examId}/sections`,
  },
  SECTIONS: {
    LIST: "/sections",
    DETAIL: (id) => `/sections/${id}`,
    CREATE: "/sections",
    UPDATE: (id) => `/sections/${id}`,
    DELETE: (id) => `/sections/${id}`,
    BY_EXAM: (examId) => `/sections?examId=${examId}`,
  },
};

// HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

export * from "./visibility"
export * from "./options"