import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Clock3, Menu, RefreshCw, UserCheck, UserX } from 'lucide-react';
import { createElement, useCallback, useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Button } from '../../../shared/components/ui';
import { AssistantShiftAvatar, AssistantShiftMiniCalendar } from '../../assistantShift/components';
import { useAssistantShiftWorkspace } from '../../assistantShift/layouts/AssistantShiftWorkspaceContext';
import { AssistantShiftRegistrationDetailModal } from '../../assistantShiftRegistration/components';
import { selectProfile } from '../../profile/store/profileSlice';
import { MyAssistantMonthView, MyAssistantScheduleMobileCalendar, MyAssistantWeekView } from '../components';
import { getMyAssistantMonthlyStatisticsAsync, getMyAssistantScheduleAsync, selectMyAssistantSchedule, selectMyAssistantScheduleError, selectMyAssistantScheduleLoading, selectMyAssistantScheduleView, selectMyAssistantStatistics, selectMyAssistantStatisticsLoading, setMyAssistantScheduleView } from '../store/myAssistantScheduleSlice';

const mondayOf = (value) => { const date = new Date(value); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; };
const daysFrom = (start, count) => Array.from({ length: count }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; });
const dayString = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const monthGrid = (date) => { const first = new Date(date.getFullYear(), date.getMonth(), 1); return daysFrom(mondayOf(first), 42); };
const title = (mode, date, days) => mode === 'week' ? `${days[0].getDate()}/${days[0].getMonth() + 1} – ${days[6].getDate()}/${days[6].getMonth() + 1}/${days[6].getFullYear()}` : `Tháng ${date.getMonth() + 1}/${date.getFullYear()}`;
const monthLabel = (date) => `Tháng ${date.getMonth() + 1}, ${date.getFullYear()}`;
const formatHours = (value) => `${Number(value || 0).toLocaleString('vi-VN', { maximumFractionDigits: 2 })} giờ`;
const dateFromString = (value) => new Date(`${value}T00:00:00`);
const viewFor = (mode, value) => { const cursor = new Date(value); const days = mode === 'week' ? daysFrom(mondayOf(cursor), 7) : monthGrid(cursor); return { mode, cursor: dayString(cursor), startAt: dayString(days[0]), endAt: dayString(days[days.length - 1]) }; };

export const MyAssistantSchedulePage = () => {
  const dispatch = useDispatch(); const { openMobileSidebar } = useAssistantShiftWorkspace();
  const profile = useSelector(selectProfile); const shifts = useSelector(selectMyAssistantSchedule); const statistics = useSelector(selectMyAssistantStatistics); const loading = useSelector(selectMyAssistantScheduleLoading); const loadingStats = useSelector(selectMyAssistantStatisticsLoading); const error = useSelector(selectMyAssistantScheduleError); const view = useSelector(selectMyAssistantScheduleView);
  const mode = view.mode; const cursor = useMemo(() => dateFromString(view.cursor), [view.cursor]); const setView = useCallback((nextMode, nextCursor) => dispatch(setMyAssistantScheduleView(viewFor(nextMode, nextCursor))), [dispatch]);
  const days = useMemo(() => mode === 'week' ? daysFrom(mondayOf(cursor), 7) : monthGrid(cursor), [cursor, mode]);
  const loadSchedule = useCallback(() => dispatch(getMyAssistantScheduleAsync({ startAt: view.startAt, endAt: view.endAt })), [dispatch, view.endAt, view.startAt]);
  useEffect(() => { loadSchedule(); }, [loadSchedule]); useEffect(() => { dispatch(getMyAssistantMonthlyStatisticsAsync()); }, [dispatch]);
  const [monthPickerOpen, setMonthPickerOpen] = useState(false); const [detailShift, setDetailShift] = useState(null); const [today] = useState(() => new Date());
  const move = (offset) => setView(mode, mode === 'week' ? new Date(cursor.getFullYear(), cursor.getMonth(), cursor.getDate() + offset * 7) : new Date(cursor.getFullYear(), cursor.getMonth() + offset, 1));
  const stats = [{ label: 'Ca đã đi', value: statistics?.workedShiftCount || 0, icon: UserCheck, color: 'text-emerald-600' }, { label: 'Giờ đã đi', value: formatHours(statistics?.workedHours), icon: Clock3, color: 'text-blue-600' }, { label: 'Ca vắng', value: statistics?.absentShiftCount || 0, icon: UserX, color: 'text-red-600' }, { label: 'Giờ vắng', value: formatHours(statistics?.absentHours), icon: Clock3, color: 'text-amber-600' }];

  return <div className="flex h-full min-h-0 flex-col bg-slate-50 md:gap-4 md:bg-transparent"><h1 className="sr-only">Lịch của tôi</h1><div className="sticky top-0 z-40 shrink-0 bg-white shadow-sm md:hidden"><div className="flex h-14 items-center gap-1 px-2"><button type="button" onClick={openMobileSidebar} aria-label="Mở menu lịch trợ giảng" className="rounded-lg p-2 text-slate-800 hover:bg-slate-100"><Menu className="h-5 w-5" /></button><button type="button" onClick={() => setMonthPickerOpen((value) => !value)} className="flex min-w-0 flex-1 items-center gap-0.5 rounded-lg px-1.5 py-2 text-left hover:bg-slate-50"><span className="max-w-[112px] truncate text-sm font-bold text-slate-900">{monthLabel(cursor)}</span><ChevronDown className={`h-3.5 w-3.5 shrink-0 text-slate-600 transition ${monthPickerOpen ? 'rotate-180' : ''}`} /></button><div className="flex shrink-0 rounded-lg bg-slate-100 p-0.5"><button type="button" onClick={() => setView('week', cursor)} className={`rounded-md px-2 py-1 text-[11px] font-bold ${mode === 'week' ? 'bg-white text-blue-700 shadow-sm' : 'text-slate-500'}`}>Tuần</button><button type="button" onClick={() => setView('month', cursor)} className={`rounded-md px-2 py-1 text-[11px] font-bold ${mode === 'month' ? 'bg-white text-blue-700 shadow-sm' : 'text-slate-500'}`}>Tháng</button></div><button type="button" onClick={() => setView(mode, today)} aria-label="Về hôm nay" className="ml-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-700 hover:bg-blue-200">{today.getDate()}</button><AssistantShiftAvatar admin={profile} sizeClass="h-8 w-8" textClass="text-[10px]" /></div>{monthPickerOpen && <div className="absolute inset-x-0 top-full border-b border-slate-200 bg-white px-3 pb-3 shadow-lg">{mode === 'week' ? <AssistantShiftMiniCalendar key={`week-${cursor.toISOString()}`} selectedWeekStart={mondayOf(cursor)} onSelectWeek={(value) => { setView('week', value); setMonthPickerOpen(false); }} /> : <AssistantShiftMiniCalendar key={`month-${cursor.toISOString()}`} mode="month" selectedMonth={cursor} onSelectMonth={(value) => { setView('month', value); setMonthPickerOpen(false); }} />}</div>}</div>
    <div className="hidden shrink-0 flex-col gap-4 lg:flex-row lg:items-end lg:justify-between md:flex"><div><p className="text-sm font-medium text-blue-600">CÁ NHÂN</p><h2 className="mt-1 text-2xl font-semibold text-foreground">Lịch của tôi</h2><p className="mt-1 text-sm text-foreground-light">Các ca bạn đã được phân công, kể cả ca hoặc chuỗi lịch đã khóa.</p></div><div className="flex flex-wrap items-center gap-2"><Button variant="outline" size="sm" onClick={() => setView(mode, new Date())}>Hôm nay</Button><div className="flex items-center rounded-sm border border-border bg-white"><button type="button" aria-label="Lùi lịch" onClick={() => move(-1)} className="p-2 hover:bg-gray-50"><ChevronLeft className="h-4 w-4" /></button><span className="min-w-44 px-2 text-center text-sm font-medium">{title(mode, cursor, days)}</span><button type="button" aria-label="Tiến lịch" onClick={() => move(1)} className="p-2 hover:bg-gray-50"><ChevronRight className="h-4 w-4" /></button></div><div className="flex rounded-sm border border-border bg-white p-0.5"><button type="button" onClick={() => setView('week', cursor)} className={`rounded px-3 py-1.5 text-xs font-medium ${mode === 'week' ? 'bg-blue-600 text-white' : 'text-foreground-light'}`}>Tuần</button><button type="button" onClick={() => setView('month', cursor)} className={`rounded px-3 py-1.5 text-xs font-medium ${mode === 'month' ? 'bg-blue-600 text-white' : 'text-foreground-light'}`}>Tháng</button></div><Button variant="outline" size="sm" loading={loading} onClick={loadSchedule}><RefreshCw className="h-4 w-4" />Làm mới</Button></div></div>
    {error && <div className="mx-3 mt-3 shrink-0 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700 md:mx-0 md:mt-0">Không thể tải lịch hoặc thống kê. Vui lòng thử lại.</div>}
    <div className="hidden gap-5 md:grid 2xl:min-h-0 2xl:flex-1 2xl:grid-cols-[260px_minmax(0,1fr)]"><aside className="space-y-4 rounded-xl border border-border bg-white p-4 shadow-sm"><div><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-blue-600" /><h2 className="font-semibold">Thống kê tháng này</h2></div><p className="mt-1 text-xs text-foreground-light">Theo thời điểm máy chủ.</p></div><div className="space-y-2">{stats.map(({ label, value, icon, color }) => <div key={label} className="rounded-lg border border-border bg-gray-50 p-3"><div className="flex items-center gap-2 text-xs text-foreground-light">{createElement(icon, { className: `h-4 w-4 ${color}` })}{label}</div><p className="mt-1 text-xl font-semibold text-foreground">{loadingStats ? '—' : value}</p></div>)}</div><p className="text-xs leading-relaxed text-foreground-light">Chỉ trạng thái Đã đi và Vắng được tính. Ca chưa đi không ảnh hưởng đến thống kê.</p></aside>{mode === 'week' ? <MyAssistantWeekView days={days} shifts={shifts} loading={loading} /> : <MyAssistantMonthView days={days} cursor={cursor} shifts={shifts} loading={loading} />}</div>
    <div className="min-h-0 flex-1 md:hidden">{mode === 'week' ? <MyAssistantScheduleMobileCalendar days={days} shifts={shifts} loading={loading} onOpenDetail={(shift) => setDetailShift({ ...shift, openedAt: new Date().toISOString() })} /> : <MyAssistantMonthView days={days} cursor={cursor} shifts={shifts} loading={loading} />}</div>
    <AssistantShiftRegistrationDetailModal shift={detailShift} profile={profile} actionShiftId={null} canRegister={false} canCancel={false} canTransfer={false} canSwap={false} onClose={() => setDetailShift(null)} onRegister={() => {}} onCancel={() => {}} onTransfer={() => {}} onSwap={() => {}} />
  </div>;
};
