/* eslint-disable no-unused-vars */
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, RefreshCw, UserCheck, UserX } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Button } from '../../../shared/components/ui';
import { MyAssistantMonthView, MyAssistantWeekView } from '../components';
import { getMyAssistantMonthlyStatisticsAsync, getMyAssistantScheduleAsync, selectMyAssistantSchedule, selectMyAssistantScheduleError, selectMyAssistantScheduleLoading, selectMyAssistantStatistics, selectMyAssistantStatisticsLoading } from '../store/myAssistantScheduleSlice';

const mondayOf = (value) => { const date = new Date(value); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; };
const daysFrom = (start, count) => Array.from({ length: count }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date; });
const dayString = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const monthGrid = (date) => { const first = new Date(date.getFullYear(), date.getMonth(), 1); return daysFrom(mondayOf(first), 42); };
const title = (mode, date, days) => mode === 'week' ? `${days[0].getDate()}/${days[0].getMonth() + 1} – ${days[6].getDate()}/${days[6].getMonth() + 1}/${days[6].getFullYear()}` : `Tháng ${date.getMonth() + 1}/${date.getFullYear()}`;
const formatHours = (value) => `${Number(value || 0).toLocaleString('vi-VN', { maximumFractionDigits: 2 })} giờ`;

export const MyAssistantSchedulePage = () => {
  const dispatch = useDispatch(); const shifts = useSelector(selectMyAssistantSchedule); const statistics = useSelector(selectMyAssistantStatistics); const loading = useSelector(selectMyAssistantScheduleLoading); const loadingStats = useSelector(selectMyAssistantStatisticsLoading); const error = useSelector(selectMyAssistantScheduleError);
  const [mode, setMode] = useState('week'); const [cursor, setCursor] = useState(() => new Date());
  const days = useMemo(() => mode === 'week' ? daysFrom(mondayOf(cursor), 7) : monthGrid(cursor), [cursor, mode]);
  const loadSchedule = useCallback(() => dispatch(getMyAssistantScheduleAsync({ startAt: dayString(days[0]), endAt: dayString(days[days.length - 1]) })), [days, dispatch]);
  useEffect(() => { loadSchedule(); }, [loadSchedule]); useEffect(() => { dispatch(getMyAssistantMonthlyStatisticsAsync()); }, [dispatch]);
  const move = (offset) => setCursor((current) => mode === 'week' ? new Date(current.getFullYear(), current.getMonth(), current.getDate() + offset * 7) : new Date(current.getFullYear(), current.getMonth() + offset, 1));
  const stats = [{ label: 'Ca có mặt', value: statistics?.workedShiftCount || 0, icon: UserCheck, color: 'text-emerald-600' }, { label: 'Giờ có mặt', value: formatHours(statistics?.workedHours), icon: Clock3, color: 'text-blue-600' }, { label: 'Ca nghỉ', value: statistics?.absentShiftCount || 0, icon: UserX, color: 'text-red-600' }, { label: 'Giờ nghỉ', value: formatHours(statistics?.absentHours), icon: Clock3, color: 'text-amber-600' }];
  return <div className="flex min-h-full flex-col gap-4 2xl:h-full 2xl:min-h-0 2xl:overflow-hidden"><div className="flex shrink-0 flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-blue-600">CÁ NHÂN</p><h1 className="mt-1 text-2xl font-semibold text-foreground">Lịch của tôi</h1><p className="mt-1 text-sm text-foreground-light">Các ca bạn đã được phân công, kể cả ca hoặc chuỗi lịch đã khóa.</p></div><div className="flex flex-wrap items-center gap-2"><Button variant="outline" size="sm" onClick={() => setCursor(new Date())}>Hôm nay</Button><div className="flex items-center rounded-sm border border-border bg-white"><button type="button" aria-label="Lùi lịch" onClick={() => move(-1)} className="p-2 hover:bg-gray-50"><ChevronLeft className="h-4 w-4" /></button><span className="min-w-44 px-2 text-center text-sm font-medium">{title(mode, cursor, days)}</span><button type="button" aria-label="Tiến lịch" onClick={() => move(1)} className="p-2 hover:bg-gray-50"><ChevronRight className="h-4 w-4" /></button></div><div className="flex rounded-sm border border-border bg-white p-0.5"><button type="button" onClick={() => setMode('week')} className={`rounded px-3 py-1.5 text-xs font-medium ${mode === 'week' ? 'bg-blue-600 text-white' : 'text-foreground-light'}`}>Tuần</button><button type="button" onClick={() => setMode('month')} className={`rounded px-3 py-1.5 text-xs font-medium ${mode === 'month' ? 'bg-blue-600 text-white' : 'text-foreground-light'}`}>Tháng</button></div><Button variant="outline" size="sm" loading={loading} onClick={loadSchedule}><RefreshCw className="h-4 w-4" />Làm mới</Button></div></div>
    {error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">Không thể tải lịch hoặc thống kê. Vui lòng thử lại.</div>}
    <div className="grid gap-5 2xl:min-h-0 2xl:flex-1 2xl:grid-cols-[260px_minmax(0,1fr)]"><aside className="space-y-4 rounded-xl border border-border bg-white p-4 shadow-sm"><div><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-blue-600" /><h2 className="font-semibold">Thống kê tháng này</h2></div><p className="mt-1 text-xs text-foreground-light">Theo thời điểm máy chủ.</p></div><div className="space-y-2">{stats.map(({ label, value, icon: Icon, color }) => <div key={label} className="rounded-lg border border-border bg-gray-50 p-3"><div className="flex items-center gap-2 text-xs text-foreground-light"><Icon className={`h-4 w-4 ${color}`} />{label}</div><p className="mt-1 text-xl font-semibold text-foreground">{loadingStats ? '—' : value}</p></div>)}</div><p className="text-xs leading-relaxed text-foreground-light">Chỉ trạng thái Có mặt và Vắng được tính. Ca đang chờ không ảnh hưởng đến thống kê.</p></aside>{mode === 'week' ? <MyAssistantWeekView days={days} shifts={shifts} loading={loading} /> : <MyAssistantMonthView days={days} cursor={cursor} shifts={shifts} loading={loading} />}</div>
  </div>;
};
